import type { EngineerPersona } from './engineering-orchestrator.ts';
type Check = { check:string; fault:string; healthy:string; blocks:boolean; faultValues:Record<string,unknown>; healthyValues:Record<string,unknown> };
export type DemoScenario = { id:string; name:string; description:string; roles:EngineerPersona[]; owner:EngineerPersona; severity:'P1'|'P2'; repair:string; checks:Partial<Record<EngineerPersona,Check>> };
const check=(check:string,fault:string,healthy:string,blocks:boolean,faultValues:Record<string,unknown>={},healthyValues:Record<string,unknown>={}):Check=>({check,fault,healthy,blocks,faultValues,healthyValues});
const path=check('interface status, packet loss and application reachability','The network path is up with no packet loss.','The network path remains up with no packet loss.',false,{interfaces:'UP',packetLossPercent:0},{interfaces:'UP',packetLossPercent:0});
const host=check('host service state and operating system errors','The host service is running; the dependency failure is outside the host.','The host service is running without dependency errors.',false,{serviceStatus:'RUNNING'},{serviceStatus:'RUNNING'});
const s=(id:string,name:string,owner:EngineerPersona,checks:DemoScenario['checks'],repair:string,severity:'P1'|'P2'='P2'):DemoScenario=>({id,name,description:`${name}. Compare each team's observations before approving a sandbox repair.`,roles:Object.keys(checks) as EngineerPersona[],owner,severity,repair,checks});
export const demoScenarios:DemoScenario[]=[
  s('false-network-middleware','False Network Symptom — Middleware Connection Exhaustion','MIDDLEWARE',{
    NETWORK:check('DNS resolution, packet loss, and application path latency','DNS resolves checkout.internal, packet loss is 0%, and path latency is within baseline.','DNS resolves checkout.internal, packet loss is 0%, and path latency is within baseline.',false,{dnsReachable:true,packetLossPercent:0,pathLatencyMs:18,networkHypothesis:'ELIMINATED'},{dnsReachable:true,packetLossPercent:0,pathLatencyMs:18,networkHypothesis:'ELIMINATED'}),
    MIDDLEWARE:check('application service state and connection-pool utilization','The application service is running, but 198 of 200 pool connections are active and requests are waiting.','The application service is running, 62 of 200 pool connections are active, and no requests are waiting.',true,{serviceStatus:'RUNNING',activeConnections:198,maxConnections:200,waitingRequests:17,poolHypothesis:'SUPPORTED'},{serviceStatus:'RUNNING',activeConnections:62,maxConnections:200,waitingRequests:0,poolHypothesis:'ELIMINATED'}),
    DATABASE:check('active sessions, wait state, and database latency','Database sessions, wait state, and query latency are within the normal operating baseline; database saturation is not observed.','Database sessions, wait state, and query latency remain within the normal operating baseline.',false,{activeConnections:48,maxConnections:400,waitingRequests:0,queryLatencyMs:21,databaseHypothesis:'ELIMINATED'},{activeConnections:48,maxConnections:400,waitingRequests:0,queryLatencyMs:21,databaseHypothesis:'ELIMINATED'})
  },'Increase the application connection-pool capacity within the approved sandbox change, recycle the affected application instance, and verify that waiting requests clear.','P1'),
  s('windows-dns','Windows DNS did not restart after patching','WINDOWS',{
    NETWORK:check('interfaces and DNS reachability','Interfaces are up, but DNS is unreachable.','Interfaces are up and DNS is reachable.',false,{interfaces:'UP',dnsReachable:false,packetLossPercent:0},{interfaces:'UP',dnsReachable:true,packetLossPercent:0}),
    WINDOWS:check('DNS service state after maintenance','The DNS service is stopped.','The DNS service is running.',true,{dnsService:'STOPPED'},{dnsService:'RUNNING'})},'Restore the DNS service state in the sandbox, then recheck name resolution.','P1'),
  s('database-pool','Orders delayed by a saturated database pool','DATABASE',{
    DATABASE:check('active connections, waiters and query latency','All 120 connections are occupied; 36 requests are waiting.','24 of 120 connections are occupied; no requests are waiting.',true,{activeConnections:120,maxConnections:120,waitingRequests:36,queryLatencyMs:2500},{activeConnections:24,maxConnections:120,waitingRequests:0,queryLatencyMs:18}),
    LINUX:host,NETWORK:path},'Restore healthy pool values and verify that waiting orders clear.','P1'),
  s('network-vlan','Users cannot reach an application after a VLAN change','NETWORK',{
    NETWORK:check('access VLAN against the assigned application segment','The access VLAN is 230; the expected VLAN is 220.','The access VLAN matches expected VLAN 220.',true,{accessVlan:230,expectedVlan:220},{accessVlan:220,expectedVlan:220}),WINDOWS:host},'Correct the sandbox VLAN assignment and verify application access.'),
  s('network-roaming','Wireless clients lose their session while roaming','NETWORK',{
    NETWORK:check('AP handoff interruption and session continuity','The handoff interrupts traffic for 1800 ms and drops the session.','The handoff interruption is 45 ms and the session is preserved.',true,{handoffInterruptionMs:1800,sessionPreserved:false},{handoffInterruptionMs:45,sessionPreserved:true}),WINDOWS:check('authentication service availability','Authentication is available throughout the handoff.','Authentication remains available.',false)},'Restore the sandbox handoff profile and verify session continuity. These values are demo observations, not agreed XLA targets.'),
  s('network-mtu','Large application requests fail across a tunnel','NETWORK',{
    NETWORK:check('path MTU and large-packet delivery','The path supports 1400 bytes; 1500-byte packets are dropped.','The path supports the configured packet size.',true,{pathMtu:1400,packetSize:1500,largePacketDelivered:false},{pathMtu:1400,packetSize:1400,largePacketDelivered:true}),LINUX:host},'Align the sandbox packet size with path MTU and repeat delivery checks.'),
  s('windows-kerberos','Kerberos sign-in fails because of host clock drift','WINDOWS',{
    WINDOWS:check('clock offset and Kerberos result','Clock offset is 420 seconds and Kerberos authentication fails.','Clock offset is 2 seconds and Kerberos authentication succeeds.',true,{clockOffsetSeconds:420,kerberosSuccess:false},{clockOffsetSeconds:2,kerberosSuccess:true}),NETWORK:path},'Restore time synchronization values in the sandbox and repeat authentication.'),
  s('windows-iis','IIS application pool remains stopped after deployment','WINDOWS',{
    WINDOWS:check('IIS application pool and HTTP response','The application pool is stopped and HTTP returns 503.','The application pool is running and HTTP returns 200.',true,{applicationPool:'STOPPED',httpStatus:503},{applicationPool:'RUNNING',httpStatus:200}),DEVOPS:host},'Restore the sandbox application pool and verify the HTTP response.'),
  s('database-lock','A long transaction blocks order processing','DATABASE',{
    DATABASE:check('blocking transaction and query wait duration','Transaction demo-tx-42 blocks 18 requests for 180 seconds.','No blocking transaction or waiting request remains.',true,{blockingTransaction:'demo-tx-42',blockedRequests:18,waitSeconds:180},{blockingTransaction:null,blockedRequests:0,waitSeconds:0}),LINUX:host},'Clear the fictional blocking transaction record and verify order processing.'),
  s('database-replica','Read replica is behind the primary','DATABASE',{
    DATABASE:check('replication delay and replay state','Replication replay is paused and the replica is 600 seconds behind.','Replay is active and the replica is 1 second behind.',true,{replicaLagSeconds:600,replayState:'PAUSED'},{replicaLagSeconds:1,replayState:'ACTIVE'}),NETWORK:path},'Restore the sandbox replay state and verify replication delay.'),
  s('database-disk','Database writes fail because the log volume is full','DATABASE',{
    DATABASE:check('write availability and log volume utilization','The log volume is 100% utilized and writes fail.','The log volume is 65% utilized and writes succeed.',true,{logVolumeUsedPercent:100,writesAvailable:false},{logVolumeUsedPercent:65,writesAvailable:true}),LINUX:check('filesystem mount state','The log filesystem is mounted; capacity recovery belongs to the DBA.','The filesystem remains mounted and writable.',false)},'Restore available log capacity in the sandbox and verify writes.'),
  s('linux-disk','Application logs fill the Linux root filesystem','LINUX',{
    LINUX:check('filesystem utilization and log rotation','Root usage is 100% and log rotation is disabled.','Root usage is 58% and log rotation is active.',true,{rootUsedPercent:100,logRotation:'DISABLED'},{rootUsedPercent:58,logRotation:'ACTIVE'}),DEVOPS:host},'Restore the sandbox log rotation and filesystem capacity values.'),
  s('linux-service','A systemd service fails after a configuration change','LINUX',{
    LINUX:check('systemd service state and configuration validation','The service failed because the configuration check reports an invalid port.','The configuration is valid and the service is running.',true,{serviceStatus:'FAILED',configurationValid:false},{serviceStatus:'RUNNING',configurationValid:true}),NETWORK:path},'Restore valid sandbox service configuration and verify service health.'),
  s('linux-permissions','Application cannot read a mounted data directory','LINUX',{
    LINUX:check('application identity and directory access','The application identity cannot read its data directory.','The application identity can read its data directory.',true,{directoryReadable:false},{directoryReadable:true}),DATABASE:host},'Restore the fictional directory permission and verify read access.'),
  s('cloud-route','A cloud subnet route sends traffic to the wrong next hop','CLOUDOPS',{
    CLOUDOPS:check('subnet route and next-hop reachability','The route points to a retired virtual appliance.','The route points to the active virtual appliance.',true,{nextHop:'demo-retired-appliance',reachable:false},{nextHop:'demo-active-appliance',reachable:true}),NETWORK:path},'Restore the expected sandbox cloud next hop and verify reachability.'),
  s('cloud-capacity','Cloud scale-out is blocked by an instance quota','CLOUDOPS',{
    CLOUDOPS:check('instance quota and pending capacity requests','The quota is 10 and all 10 slots are occupied; 2 instances are pending.','The quota is 12 and all requested instances are allocated.',true,{quota:10,pendingInstances:2},{quota:12,pendingInstances:0}),DEVOPS:host},'Update the sandbox capacity allowance and verify pending instances clear.'),
  s('cloud-health','Load balancer health checks target the wrong port','CLOUDOPS',{
    CLOUDOPS:check('load balancer probe port and backend health','Probes use port 8081 while the service listens on 8080; backends are unhealthy.','Probes use port 8080 and backends are healthy.',true,{probePort:8081,servicePort:8080,backendHealthy:false},{probePort:8080,servicePort:8080,backendHealthy:true}),LINUX:host},'Correct the sandbox probe port and verify backend health.'),
  s('devops-image','Release rollout fails to pull a container image','DEVOPS',{
    DEVOPS:check('release image reference and rollout status','The image tag is absent and the rollout is blocked.','The image tag exists and the rollout is healthy.',true,{imageExists:false,rollout:'ImagePullBackOff'},{imageExists:true,rollout:'HEALTHY'}),CLOUDOPS:host},'Restore the sandbox image reference and verify rollout status.'),
  s('devops-readiness','A release uses the wrong readiness endpoint','DEVOPS',{
    DEVOPS:check('readiness path and deployment health','The readiness path returns 404 and no replicas are ready.','The readiness path returns 200 and three replicas are ready.',true,{readinessHttpStatus:404,readyReplicas:0},{readinessHttpStatus:200,readyReplicas:3}),LINUX:host},'Restore the expected sandbox readiness path and verify ready replicas.'),
  s('middleware-queue','Messages accumulate because a queue consumer is stopped','MIDDLEWARE',{
    MIDDLEWARE:check('consumer count, queue depth and delivery','No consumer is active and 500 messages are queued.','One consumer is active and the queue is drained.',true,{activeConsumers:0,queueDepth:500},{activeConsumers:1,queueDepth:0}),LINUX:host,DATABASE:host},'Restore the fictional consumer state and verify queued messages drain.'),
  s('security-certificate','An expired service certificate blocks TLS access','SECURITY',{
    SECURITY:check('certificate validity and TLS handshake','The service certificate has expired and TLS validation fails.','The certificate is valid and the TLS handshake succeeds.',true,{certificateValid:false,tlsHandshake:false},{certificateValid:true,tlsHandshake:true}),WINDOWS:host,NETWORK:path},'Replace the certificate state in the sandbox and verify the TLS handshake.')
  ,s('cross-functional-checkout','Checkout requests fail across Windows, DevOps, Network and Linux','DEVOPS',{
    WINDOWS:check('checkout host service and event errors','The checkout host service is running, but recent events show dependency timeouts.','The checkout host service is running without dependency timeout errors.',false,{serviceStatus:'RUNNING',dependencyTimeouts:12},{serviceStatus:'RUNNING',dependencyTimeouts:0}),
    DEVOPS:check('release health and application dependency status','The latest checkout release reports degraded dependency health and is serving errors.','The checkout release reports healthy dependencies and serves successfully.',true,{release:'checkout-2026.09.08',dependencyHealth:'DEGRADED',httpStatus:503},{release:'checkout-2026.09.08',dependencyHealth:'HEALTHY',httpStatus:200}),
    NETWORK:check('service route, packet loss and reachability','The checkout route is reachable with no packet loss; the issue is above the network path.','The checkout route remains reachable with no packet loss.',false,{routeReachable:true,packetLossPercent:0},{routeReachable:true,packetLossPercent:0}),
    LINUX:check('worker service state and host resource pressure','The checkout worker is running and host pressure is within normal limits.','The checkout worker is running with normal host pressure.',false,{serviceStatus:'RUNNING',loadAverage:1.2},{serviceStatus:'RUNNING',loadAverage:0.4})
  },'Restore the sandbox checkout release dependency state, then have all four teams repeat their checks and correlate the recovery.','P1')
];

export function scenarioResourceState(scenario:DemoScenario,role:string,faulted:boolean) {
  const c=scenario.checks[role as EngineerPersona];
  if(!c) throw new Error('Role is not assigned to this scenario.');
  return {check:c.check,finding:faulted?c.fault:c.healthy,blocked:faulted&&c.blocks,...(faulted?c.faultValues:c.healthyValues)};
}
