"""Create seven versioned V3 datasets by adding exactly four evidence-state examples per Twin."""
import hashlib, json, math, re
from difflib import SequenceMatcher
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]; SRC=ROOT/'.data/training/domain-datasets-v2'; OUT=ROOT/'.data/training/domain-datasets-v3'; PREP=ROOT/'.data/training/prepared-domain-v3'; BENCH=ROOT/'training/benchmarks/cases'; MODEL='Qwen/Qwen3-0.6B'; REV='c1899de289a04d12100db370d81485cdf75e47ca'
def read(p): return [json.loads(x) for x in p.read_text(encoding='utf-8').splitlines() if x.strip()]
def resp(domain,tech,assessment,facts,hyps,missing,action,root,remediation,abstain,reason,esc): return {'domain':domain,'technology':tech,'vendor':'Generic','assessment':assessment,'observedFacts':facts,'hypotheses':hyps,'missingEvidence':missing,'nextDiagnosticAction':{'action':action,'reason':'Collect discriminating evidence before a configuration change.'},'toolSelection':{'tool':'Read-only domain diagnostics','reason':'Evidence collection only.'},'rootCause':root,'remediation':remediation,'risk':'Do not change production state without evidence and existing approval.','rollback':'No change is authorized until evidence supports an approved action.','verification':'Validate the next evidence against the affected and comparator scope.','abstain':abstain,'abstentionReason':reason,'escalateTo':esc}
def hyp(c,s,e): return {'cause':c,'status':s,'evidence':e}
EMPTY={'established':False,'cause':'','evidence':[]}
S={
'windows':[('SUPPORTED','Windows service latency follows Event ID 7011 timeout entries while peer services remain healthy.', 'Service timeout', 'Event ID 7011 repeats on the affected host; peer service is healthy.', 'Service dependency timeout','Windows event log and healthy peer comparison',['service dependency timeout'],['service dependency configuration and service trace'],'Collect service dependency trace for confirmation','Keep service configuration unchanged pending confirmation.',False,''),('SUPPORTED','Clients fail name resolution only through one DNS forwarder; server query logs show delayed outbound lookups.', 'DNS forwarding delay','Delayed outbound lookup entries and healthy alternate forwarder.','Forwarder latency','DNS query log and alternate-forwarder result',['delayed lookup'],['packet capture to forwarder'],'Capture one failed request and response for confirmation','Do not change DNS forwarding until the trace confirms the path.',False,''),('ELIMINATED','Authentication failures occur, but Kerberos ticket checks, secure-channel tests, and domain controller event logs are healthy.', 'Kerberos failure','Valid tickets, healthy secure channel, no domain controller errors.','Kerberos infrastructure failure','ticket and secure-channel diagnostics',['healthy tickets'],['application authentication trace'],'Do not alter Kerberos or domain controller configuration; inspect application identity handling.',False,''),('ELIMINATED','A web service is slow, but IIS worker CPU, queue length, and request logs are normal while database wait time rises.', 'IIS saturation','Normal IIS resource state and increasing database waits.','IIS worker saturation','IIS counters and request log',['normal IIS state'],['database wait analysis'],'No IIS remediation; request Database analysis of waits.',False,'',['DATABASE'])],
'linux':[('SUPPORTED','A process restarts after memory pressure; cgroup events record OOM kills while comparable nodes have headroom.','Linux memory pressure','cgroup OOM events and healthy comparator memory.','cgroup memory limit pressure','cgroup event log',['OOM kill'],['container memory profile'],'Capture workload allocation profile for confirmation','Do not change memory limits until the profile is reviewed.',False,''),('SUPPORTED','A service is unreachable after package update; journal records a failed unit start with a missing shared library.','systemd service start','journal unit failure and missing library error.','package dependency regression','journal and package version',['missing shared library'],['package dependency diff'],'Compare package dependency manifest before rollback','Hold package change until dependency diff is confirmed.',False,''),('ELIMINATED','Filesystem latency is reported, but iostat is normal and an application trace shows connection-pool wait time.','Filesystem latency','Normal disk latency and application pool wait.','storage latency','iostat and application trace',['normal disk latency'],['middleware pool telemetry'],'No filesystem change; request Middleware pool evidence.',False,'',['MIDDLEWARE']),('ELIMINATED','SSH access failures are reported, but sshd logs show successful authentication and packet capture shows sessions reach the host; the client key agent fails locally.','SSH access','successful sshd auth and completed TCP sessions.','Linux sshd failure','sshd log and capture',['successful authentication'],['endpoint key-agent evidence'],'Do not restart sshd; request endpoint investigation.',False,'',['WINDOWS'])],
'database':[('SUPPORTED','Checkout latency rises; database telemetry shows a surge in lock waits for one query while storage latency and replicas remain normal.','Database locking','lock-wait telemetry and normal storage/replica state.','lock contention','lock wait report',['lock waits'],['query execution plan'],'Capture plan and blocking session chain for confirmation','Do not terminate sessions before plan and ownership review.',False,''),('SUPPORTED','Replica lag grows; replication status shows apply delay after a bulk load while network RTT and primary commit latency remain normal.','Replication lag','apply delay and normal transport metrics.','replica apply backlog','replication status',['apply delay'],['bulk-load transaction evidence'],'Collect transaction and apply queue detail','Do not force failover while apply cause is under review.',False,''),('ELIMINATED','Connection failures are reported, but database listener accepts test sessions and logs show no rejected connections; application pool is exhausted.','Database connectivity','listener accepts sessions and no rejection logs.','database listener failure','listener test and logs',['successful listener test'],['middleware pool state'],'No database listener change; request Middleware pool evidence.',False,'',['MIDDLEWARE']),('ELIMINATED','Query slowness is reported, but plan cache and waits are normal while host DNS lookups intermittently fail before connections are opened.','Database query performance','normal plan/waits and failing pre-connection DNS.','database query regression','database telemetry and DNS trace',['normal waits'],['network DNS evidence'],'No query tuning change; request Network DNS validation.',False,'',['NETWORK'])],
'middleware':[('SUPPORTED','Message processing delays align with a growing unacknowledged count on one consumer while broker disk and database latency are normal.','Messaging consumer health','unacknowledged count rises; broker and database healthy.','consumer processing backlog','queue metrics',['unacknowledged messages'],['consumer thread dump'],'Collect consumer thread dump for confirmation','Do not restart consumers until the blocking stack is confirmed.',False,''),('SUPPORTED','Application requests fail during garbage collection pauses; JVM telemetry records long promotion pauses while downstream response times are healthy.','JVM runtime','long GC pauses and healthy downstream timing.','JVM promotion pressure','GC telemetry',['promotion pauses'],['heap occupancy profile'],'Collect heap occupancy profile for confirmation','Hold JVM tuning until heap evidence is reviewed.',False,''),('ELIMINATED','Queue backlog is reported, but consumer count, acknowledgements, and broker depth are normal; Network capture shows failed DNS resolution before publish.','Messaging backlog','normal broker/consumer metrics and DNS failures.','broker backlog','broker metrics and DNS trace',['normal acknowledgements'],['Network DNS evidence'],'No broker restart; request Network DNS validation.',False,'',['NETWORK']),('ELIMINATED','API errors are blamed on the application server, but thread pools and JVM health are normal while database deadlock telemetry rises.','Application server errors','healthy application runtime and database deadlocks.','application server saturation','runtime health and database telemetry',['healthy thread pools'],['Database deadlock evidence'],'No application-server change; request Database deadlock analysis.',False,'',['DATABASE'])],
'cloudops':[('SUPPORTED','A workload loses access to a managed service; flow logs show rejects at one security policy while route tables and service health are normal.','Cloud network policy','flow-log rejects and normal routes/service.','security policy block','flow logs',['policy reject'],['approved policy intent'],'Compare the policy rule to approved intent for confirmation','Do not broaden security policy until intent is confirmed.',False,''),('SUPPORTED','A managed instance fails health checks; platform events show a failed boot extension while load-balancer probes and network reachability are healthy.','Cloud compute health','boot extension failure and healthy probes.','instance boot extension failure','platform event',['boot extension failure'],['instance console output'],'Collect console output for confirmation','Do not recreate the instance until console evidence is reviewed.',False,''),('ELIMINATED','Cloud API timeouts are reported, but security policies, routes, and load-balancer health are normal while application traces show thread starvation.','Cloud API timeout','healthy cloud network controls and application starvation.','cloud network outage','flow/policy/health evidence',['healthy cloud path'],['Middleware thread evidence'],'No cloud network change; request Middleware runtime analysis.',False,'',['MIDDLEWARE']),('ELIMINATED','A deployment cannot reach storage, but cloud IAM audit shows successful authorization and storage logs show no denial; the pod lacks the expected credential mount.','Cloud storage access','successful IAM and storage authorization; missing pod mount.','cloud IAM denial','audit and storage logs',['authorization success'],['DevOps workload manifest'],'No IAM policy change; request DevOps manifest validation.',False,'',['DEVOPS'])],
'devops':[('SUPPORTED','A rollout stalls; Kubernetes events show readiness probe failures after an image digest change while cluster capacity and service endpoints are healthy.','Kubernetes rollout','readiness failures after digest change.','image/runtime incompatibility','event stream and digest diff',['probe failure'],['container startup log'],'Collect startup log for confirmation','Do not rollback automatically; review the image change and approval context.',False,''),('SUPPORTED','A pipeline deploys the wrong configuration; artifact metadata and rendered manifest disagree on one feature flag while source control revision is correct.','Deployment configuration','artifact metadata and manifest mismatch.','artifact configuration drift','artifact and manifest diff',['flag mismatch'],['pipeline substitution log'],'Collect substitution log for confirmation','Hold further promotion until artifact provenance is confirmed.',False,''),('ELIMINATED','A deployment fails, but rendered manifests and cluster events are healthy while the database reports authentication mapping errors.','Deployment failure','healthy manifest/events and database auth errors.','Kubernetes deployment failure','manifest and event evidence',['healthy rollout'],['Database authentication evidence'],'No deployment rollback; request Database authentication analysis.',False,'',['DATABASE']),('ELIMINATED','Pipeline timeouts are blamed on the runner, but runner CPU, disk, and queue are healthy while source-control API latency is elevated.','Pipeline timeout','healthy runner telemetry and source-control latency.','runner resource exhaustion','runner telemetry',['healthy runner'],['source-control service evidence'],'No runner resize; request Middleware/service-owner evidence.',False,'',['MIDDLEWARE'])],
'cyber':[('SUPPORTED','A privileged login alert appears; identity logs show an impossible-travel pattern and the session source is not on the approved corporate ASN list.','Identity anomaly','impossible travel and unapproved source ASN.','account misuse','identity and ASN telemetry',['impossible travel'],['MFA challenge result'],'Collect MFA and device posture evidence for confirmation','Do not disable the account automatically; follow approved containment policy.',False,''),('SUPPORTED','Endpoint alerts show a persistence registry change and a matching unsigned binary hash on the same host; known-good hosts lack both indicators.','Endpoint persistence','registry change and unsigned binary hash.','endpoint persistence','endpoint telemetry',['matching indicators'],['process lineage'],'Collect process lineage for confirmation','Do not delete artifacts before forensic preservation.',False,''),('ELIMINATED','A firewall alert is blamed on a malicious scan, but flow records match an approved vulnerability scanner window and target list.','Network scan alert','approved scanner identity, window, and target list.','malicious scanning','flow and change records',['approved scanner match'],['scanner job completion'],'No containment action; verify scanner job completion.',False,'',['NETWORK']),('ELIMINATED','Repeated authentication failures are blamed on credential stuffing, but identity logs tie them to a disabled service account after a scheduled rotation.','Authentication failures','disabled service account and scheduled rotation record.','credential stuffing','identity and change records',['rotation correlation'],['service owner confirmation'],'No user lockout action; request service owner confirmation.',False,'',['WINDOWS'])]
}
def record(twin,index,state,values):
 if len(values)==10: values=values[:7]+['Collect discriminating diagnostic evidence']+values[7:]
 summary,symptom,evidence,cause,source,evidences,missing,action,remediation,abstain,reason,*esc=values; esc=esc[0] if esc else []
 a=resp(twin.upper(),symptom,summary,[evidence],[hyp(cause,state,evidences)],missing,action,EMPTY,remediation,abstain,reason,esc)
 user=f'Patch V3 {twin} {state} {index}: {summary} Evidence: {evidence} Determine the evidence state, safe next action, and required collaborator.'
 return {'messages':[{'role':'system','content':f'You are the {twin} Twin. Use structured-contract-v2. Distinguish supported from confirmed and require evidence before change.'},{'role':'user','content':user},{'role':'assistant','content':json.dumps(a,separators=(',',':'))}], 'metadata':{'patch':'EVIDENCE_STATE_V3','state':state,'crossDomain':bool(esc),'abstention':abstain},'provenance':{'domain':twin.upper(),'incidentId':f'V3-{twin.upper()}-{state}-{index}','incidentFamily':f'{twin}:evidence-state:{state.lower()}:{index}','mode':'SIMULATION','source':'EVIDENCE_STATE_PATCH_V3'},'trainingReady':False}
def split(rows):
 groups={}
 for r in rows: groups.setdefault(r['provenance']['incidentFamily'],[]).append(r)
 keys=sorted(groups); val={k for i,k in enumerate(keys) if i%5==0}; return [r for k in keys if k not in val for r in groups[k]],[r for k in keys if k in val for r in groups[k]]
def main():
 from transformers import AutoTokenizer
 OUT.mkdir(parents=True,exist_ok=True); PREP.mkdir(parents=True,exist_ok=True); bench=[x for p in BENCH.rglob('*.jsonl') for x in read(p)]; report={}; all_answers=[]
 tok=AutoTokenizer.from_pretrained(MODEL,revision=REV,trust_remote_code=False)
 for twin,defs in S.items():
  original=read(SRC/f'{twin}-behavior-v2.jsonl'); patch=[record(twin,i+1,state,vals) for i,(state,*vals) in enumerate(defs)]; rows=original+patch; train,val=split(rows); target=OUT/f'{twin}-behavior-v3.jsonl'; target.write_text(''.join(json.dumps(r,ensure_ascii=False)+'\n' for r in rows),encoding='utf-8'); d=PREP/twin; d.mkdir(parents=True,exist_ok=True)
  for name,part in [('train.jsonl',train),('validation.jsonl',val)]: (d/name).write_text(''.join(json.dumps(r,ensure_ascii=False)+'\n' for r in part),encoding='utf-8')
  answers=[r['messages'][-1]['content'] for r in rows]; prompts=[r['messages'][1]['content'] for r in rows]; lengths=[len(tok.apply_chat_template(r['messages'],tokenize=True,add_generation_prompt=False,enable_thinking=False)) for r in rows]
  leak=[c['id'] for r in patch for c in bench if c['id'].lower() in json.dumps(r).lower() or c['scenario'].lower() in json.dumps(r).lower()]
  # Only new patch rows can introduce a new near-duplicate; compare them to
  # the preserved corpus rather than recomputing the known V2 baseline.
  near=[round(SequenceMatcher(None,p['messages'][-1]['content'],a).ratio(),4) for p in patch for a in answers if a != p['messages'][-1]['content'] and SequenceMatcher(None,p['messages'][-1]['content'],a).ratio()>=.92]
  states={x:0 for x in ('SUSPECTED','SUPPORTED','CONFIRMED','ELIMINATED','INSUFFICIENT_EVIDENCE')}
  for row in rows:
   parsed=json.loads(row['messages'][-1]['content']); hypotheses=parsed.get('hypotheses',[]) if isinstance(parsed.get('hypotheses',[]),list) else []; status={str(h.get('status','')).upper() for h in hypotheses if isinstance(h,dict)}; root=parsed.get('rootCause',{}) if isinstance(parsed.get('rootCause',{}),dict) else {}
   states['SUSPECTED']+=bool(status&{'OPEN','SUSPECTED'}); states['SUPPORTED']+=bool(status&{'SUPPORTED'}) or bool(row.get('metadata',{}).get('supportedRCA')) and not bool(root.get('established')); states['CONFIRMED']+=bool(root.get('established')) or bool(status&{'CONFIRMED'}); states['ELIMINATED']+=bool(status&{'ELIMINATED'}); states['INSUFFICIENT_EVIDENCE']+=parsed.get('abstain') is True
  gate=not (len(prompts)!=len(set(prompts)) or len(answers)!=len(set(answers)) or near or leak or set(r['provenance']['incidentFamily'] for r in train)&set(r['provenance']['incidentFamily'] for r in val) or max(lengths)>640) and all(states[x]>0 for x in states)
  readiness={'experimentReadiness':'EXPERIMENT_READY_NOT_SME_APPROVED' if gate else 'BLOCKED','readyForPilotTraining':gate,'baseModel':MODEL,'revision':REV,'maxSequenceLength':640,'trainCount':len(train),'validationCount':len(val),'sha256':{n:hashlib.sha256((d/n).read_bytes()).hexdigest() for n in ('train.jsonl','validation.jsonl')}}; (d/'readiness.json').write_text(json.dumps(readiness,indent=2),encoding='utf-8')
  report[twin]={'total':len(rows),'train':len(train),'validation':len(val),'maxTokens':max(lengths),'states':states,'exactDuplicatePrompts':len(prompts)-len(set(prompts)),'exactDuplicateResponses':len(answers)-len(set(answers)),'nearDuplicatePairs':len(near),'benchmarkLeakage':leak,'familyLeakage':bool(set(r['provenance']['incidentFamily'] for r in train)&set(r['provenance']['incidentFamily'] for r in val)),'gatesPassed':gate}; all_answers += [(twin,a) for a in answers]
 seen={}; cross=0
 for twin,answer in all_answers:
  if answer in seen and seen[answer] != twin: cross+=1
  seen[answer]=twin
 (PREP/'quality-report-v3.json').write_text(json.dumps({'datasets':report,'crossTwinExactDuplicateResponses':cross,'baseModel':MODEL,'revision':REV},indent=2),encoding='utf-8'); print(json.dumps(report,indent=2))
if __name__=='__main__': main()
