"""Audit Network v6 and build a narrowly scoped, leakage-checked v7 patch dataset."""
import hashlib, json, math, re
from collections import Counter
from difflib import SequenceMatcher
from pathlib import Path

ROOT=Path(__file__).resolve().parents[1]
V6=ROOT/'.data/training/user-proposed-prepared-network-v6'
V7=ROOT/'.data/training/user-proposed-prepared-network-v7'
BENCH=ROOT/'training/benchmarks/cases'
MODEL='Qwen/Qwen3-0.6B'; REV='c1899de289a04d12100db370d81485cdf75e47ca'

def read(path): return [json.loads(x) for x in path.read_text(encoding='utf-8').splitlines() if x.strip()]
def assistant(row):
    try: return json.loads(next(x['content'] for x in row['messages'] if x['role']=='assistant'))
    except Exception: return {}
def text(row): return json.dumps(row,ensure_ascii=False).upper()

def audit(rows):
    counts=Counter(); states=Counter()
    for row in rows:
        raw=text(row); a=assistant(row); ar=json.dumps(a,ensure_ascii=False).upper()
        initial_only='INITIAL_SIGNAL' in raw and not any(x in raw for x in ('SHOW ','PACKET CAPTURE','COUNTER','LOG ','TRACE','CONFIG'))
        incomplete=any(x in raw for x in ('INSUFFICIENT','INCOMPLETE','MISSING EVIDENCE','UNKNOWN','UNAVAILABLE'))
        dependency=any(x in raw for x in ('DEPENDENCY','ESCALATETO','WINDOWS TWIN','LINUX TWIN','CLOUDOPS TWIN','MIDDLEWARE TWIN','DATABASE TWIN','CYBER TWIN'))
        multiple=isinstance(a.get('hypotheses'),list) and len(a['hypotheses'])>1
        established=any(x in ar for x in ('"STATUS": "ESTABLISHED"','"STATUS":"ESTABLISHED"','"STATUS": "CONFIRMED"','"STATUS":"CONFIRMED"')) or bool(a.get('rootCause',{}).get('established'))
        remediation=str(a.get('remediation',a.get('temporaryFix',''))).upper(); config_change=any(x in remediation for x in ('RECONFIG','CHANGE ','CORRECT ','ALIGN ','RESTART','DISABLE','ENABLE','ASSIGN ','REMOVE ','ADD '))
        cross=any(x in raw for x in ('WINDOWS','LINUX','CLOUD','MIDDLEWARE','DATABASE','CYBER','APPLICATION'))
        counts['initialSignalOnly']+=initial_only; counts['incompleteEvidence']+=incomplete; counts['dependencyEvidenceMissing']+=cross and not dependency
        counts['multipleHypotheses']+=multiple; counts['establishedWithInsufficientEvidence']+=established and (initial_only or incomplete)
        counts['configurationRemediationBeforeRCASupport']+=config_change and (initial_only or incomplete) and not established
        counts['abstentionMissing']+='abstain' not in a; counts['crossTwinEscalationMissing']+=cross and not a.get('escalateTo')
        for state in ('INSUFFICIENT_EVIDENCE','SUSPECTED','SUPPORTED','CONFIRMED','ELIMINATED'):
            states[state]+=state in ar
        states['CROSS_TWIN_ESCALATION']+=bool(a.get('escalateTo'))
    return {'records':len(rows),'patternCounts':dict(counts),'explicitBehaviorCounts':dict(states),'method':'deterministic lexical/structural audit; counts are indicators for review, not SME findings'}

SYSTEM='You are the CloudZero Network Twin. Follow structured-contract-v2. Use only supplied evidence. Keep hypotheses SUSPECTED until discriminating evidence supports them. Abstain with INSUFFICIENT_EVIDENCE when RCA cannot be established. Never prescribe configuration changes from an initial signal alone. Populate escalateTo when another Twin must participate. Return only one JSON object.'
def response(domain,technology,assessment,facts,hypotheses,missing,action,tool,root,remediation,risk,rollback,verification,abstain,reason,escalate):
    return {'domain':domain,'technology':technology,'vendor':'Generic','assessment':assessment,'observedFacts':facts,'hypotheses':hypotheses,'missingEvidence':missing,'nextDiagnosticAction':{'action':action,'reason':'Obtain discriminating evidence before changing configuration.'},'toolSelection':{'tool':tool,'reason':'Read-only evidence collection.'},'rootCause':root,'remediation':remediation,'risk':risk,'rollback':rollback,'verification':verification,'abstain':abstain,'abstentionReason':reason,'escalateTo':escalate}
def hyp(cause,status,evidence): return {'cause':cause,'status':status,'evidence':evidence}
EMPTY={'established':False,'cause':'','evidence':[]}
def item(i,family,user,answer,split):
    return {'messages':[{'role':'system','content':SYSTEM},{'role':'user','content':user},{'role':'assistant','content':json.dumps(answer,separators=(',',':'))}], 'provenance':{'domain':'Network','incidentId':f'PATCH-NET-{i:02d}','incidentFamily':family,'mode':'SIMULATION','source':'NETWORK_ABSTENTION_PATCH_V1','reviewDecision':'EXPERIMENTAL_NOT_SME_APPROVED','splitIntent':split,'correctionHistory':[]},'promptHash':hashlib.sha256(user.encode()).hexdigest()}

def patch_rows():
    rows=[]
    def add(i,f,u,a,s='train'): rows.append(item(i,f,u,a,s))
    add(1,'Patch:DHCP_AMBIGUOUS','One wireless client reports an APIPA address. Only the initial helpdesk signal is available; association, relay, scope, and packet evidence are absent.',response('Network','DHCP','INSUFFICIENT_EVIDENCE: one client symptom does not establish a DHCP relay failure.', ['One client reports an APIPA address'],[hyp('DHCP path or client issue','SUSPECTED',[])],['association state','DHCP discover/offer capture','relay counters','scope availability'],'Collect association state and a DHCP transaction capture','Wireless and DHCP telemetry',EMPTY,'No configuration change; collect evidence and correlate with the Windows DHCP Twin.','Changing relay or scope settings could disrupt unaffected clients.','Not applicable until an approved evidence-supported change exists.','Confirm whether discover reaches the relay and whether an offer returns.',True,'RCA cannot be established from the initial signal.',['WINDOWS']))
    add(2,'Patch:DHCP_CONFIRMED','Multiple clients on one WLAN fail DHCP. A capture shows DISCOVER frames reach the gateway but no relay-forward packets leave it; the running configuration lacks the approved helper address.',response('Network','DHCP','The missing approved helper address is CONFIRMED by configuration and packet evidence.',['DISCOVER reaches gateway','No relay-forward packet','Approved helper address absent'],[hyp('Missing DHCP helper address','CONFIRMED',['packet capture','running configuration'])],[],'Verify the intended helper address against source of truth','Packet capture and configuration diff',{'established':True,'cause':'Missing DHCP helper address','evidence':['No relay-forward packet','Approved helper address absent']},'After approval, restore the approved helper address.','An incorrect helper can misdirect DHCP traffic.','Restore the prior gateway configuration if validation fails.','Observe relay-forward and OFFER/ACK completion for affected clients.',False,'',['WINDOWS']))
    add(3,'Patch:DNS_AMBIGUOUS','Users report intermittent failure resolving an internal name. No query logs, authoritative answers, client resolver traces, or transport tests are supplied.',response('Network','DNS','INSUFFICIENT_EVIDENCE: DNS server, client, and transport causes remain viable.', ['Intermittent internal-name resolution is reported'],[hyp('Authoritative DNS issue','SUSPECTED',[]),hyp('Client resolver issue','SUSPECTED',[]),hyp('Network path issue','SUSPECTED',[])],['client resolver trace','authoritative query log','direct query results','packet loss test'],'Collect synchronized client and authoritative DNS evidence','DNS diagnostics',EMPTY,'No configuration change; compare direct queries and server logs first.','Changing DNS records without evidence can broaden impact.','No rollback is needed for read-only diagnostics.','Reproduce the query and correlate request and response across client, network, and server. ',True,'Multiple plausible causes remain.',['WINDOWS']))
    add(4,'Patch:DNS_CONFIRMED','Direct queries to both authoritative nodes return different A records. Zone serials differ and the secondary transfer log records a rejected update.',response('Network','DNS','Authoritative zone divergence is CONFIRMED by serial and answer differences.',['Different authoritative answers','Zone serial mismatch','Rejected transfer logged'],[hyp('Secondary zone is stale','CONFIRMED',['serial mismatch','rejected transfer'])],[],'Validate transfer authorization and approved primary serial','Authoritative DNS logs',{'established':True,'cause':'Rejected zone transfer left the secondary stale','evidence':['Zone serial mismatch','Rejected transfer logged']},'After approval, correct transfer authorization and synchronize the secondary.','An incorrect transfer change can affect authoritative service.','Restore the previous authorization and zone copy if synchronization fails.','Both authorities return the approved record and matching serial. ',False,'',['WINDOWS']))
    add(5,'Patch:APP_TIMEOUT_AMBIGUOUS','An application dashboard reports timeout errors. No flow telemetry, packet capture, server saturation data, or dependency timing is available.',response('Network','Connectivity','INSUFFICIENT_EVIDENCE: an application timeout alone does not prove a Network RCA.',['Application timeout alert'],[hyp('Network path degradation','SUSPECTED',[]),hyp('Application saturation','SUSPECTED',[]),hyp('Database latency','SUSPECTED',[])],['five-tuple flow telemetry','client/server timing','application saturation','database latency'],'Collect synchronized flow and service timing','Flow telemetry',EMPTY,'No network configuration change; correlate service and path evidence.','Blind network changes can add outage risk.','No rollback is needed for read-only collection.','Separate transport delay from server processing time. ',True,'The symptom spans multiple domains without discriminating evidence.',['MIDDLEWARE','DATABASE']))
    add(6,'Patch:APP_TIMEOUT_NETWORK_SUPPORTED','Application timeouts align with rising retransmissions on one path, interface output drops, and clean server processing time on the alternate path.',response('Network','Connectivity','Network path congestion is SUPPORTED; change still requires approval and final confirmation.',['Retransmissions on one path','Interface output drops','Alternate path has clean server timing'],[hyp('Congestion on the affected path','SUPPORTED',['retransmissions','output drops','healthy alternate path'])],['queue policy and utilization history'],'Confirm queue saturation and policy intent','Interface telemetry',EMPTY,'Keep traffic on the healthy approved path while queue evidence is reviewed; do not change policy without approval.','Traffic movement can shift congestion.','Return traffic to the previous path if health degrades.','Verify retransmissions, drops, latency, and application timeout rate. ',False,'',['MIDDLEWARE']))
    add(7,'Patch:VLAN_AMBIGUOUS','A newly moved endpoint cannot reach its service. The switch port, intended VLAN, authentication result, and MAC learning location are not supplied.',response('Network','VLAN','INSUFFICIENT_EVIDENCE: VLAN assignment, authentication, endpoint, and service causes remain possible.',['Endpoint cannot reach service after a move'],[hyp('Access VLAN mismatch','SUSPECTED',[]),hyp('Authentication policy issue','SUSPECTED',[]),hyp('Endpoint configuration issue','SUSPECTED',[])],['switchport mode and VLAN','authentication session','MAC table','endpoint addressing'],'Collect port, authentication, and endpoint state','Switch read-only commands',EMPTY,'No VLAN change until intended state and current state are compared.','Changing a VLAN blindly can violate segmentation.','No rollback is required for read-only diagnostics.','Identify the first failed layer using port, auth, address, and reachability evidence. ',True,'Current evidence cannot isolate a layer.',['WINDOWS']))
    add(8,'Patch:VLAN_CONFIRMED','The source of truth assigns VLAN 240, while show interface switchport reports access VLAN 204; the endpoint MAC is learned on that port in VLAN 204.',response('Network','VLAN','Access VLAN mismatch is CONFIRMED by intent, port state, and MAC evidence.',['Approved VLAN is 240','Port reports VLAN 204','Endpoint MAC learned in VLAN 204'],[hyp('Access VLAN mismatch','CONFIRMED',['intent diff','switchport state','MAC location'])],[],'Confirm no shared-device exception exists','Configuration compliance',{'established':True,'cause':'Access port configured for VLAN 204 instead of approved VLAN 240','evidence':['Intent is VLAN 240','Observed VLAN is 204']},'After approval, configure the access port for VLAN 240.','VLAN change briefly disrupts the endpoint.','Restore VLAN 204 if the approved change fails validation.','MAC learns in VLAN 240 and intended service reachability succeeds. ',False,'',[]))
    add(9,'Patch:VXLAN_AMBIGUOUS','A tenant reports east-west loss after maintenance. VTEP peer state, VNI mappings, EVPN routes, underlay reachability, and MAC mobility data are missing.',response('Network','VXLAN','INSUFFICIENT_EVIDENCE: overlay, control-plane, and underlay causes remain viable.',['Tenant east-west loss after maintenance'],[hyp('VNI mapping drift','SUSPECTED',[]),hyp('EVPN route issue','SUSPECTED',[]),hyp('Underlay reachability issue','SUSPECTED',[])],['VTEP peer state','VNI mappings on both ends','EVPN routes','underlay reachability'],'Collect both-end overlay and underlay state','VXLAN/EVPN show commands',EMPTY,'Do not alter VNI or routing configuration before comparing both ends.','Blind overlay changes can affect multiple tenants.','No rollback is needed for read-only collection.','Correlate peer, VNI, route, and underlay state for the affected segment. ',True,'The initial symptom does not distinguish overlay from underlay.',['CLOUDOPS']))
    add(10,'Patch:VXLAN_CONFIRMED','Both VTEPs are reachable and EVPN routes exist. The local segment maps VLAN 310 to VNI 50310 while the remote maps it to VNI 50301.',response('Network','VXLAN','The segment VNI mismatch is CONFIRMED while underlay and EVPN control plane are healthy.',['VTEPs reachable','EVPN routes present','VNI mapping differs'],[hyp('VNI mapping mismatch','CONFIRMED',['local VNI 50310','remote VNI 50301'])],[],'Validate the approved segment-to-VNI mapping','VXLAN configuration diff',{'established':True,'cause':'Inconsistent VNI mapping for the same segment','evidence':['Local and remote mapping differ']},'After approval, align the incorrect endpoint to the approved VNI.','Incorrect alignment can affect tenant isolation.','Restore the previous mapping if peer or forwarding health worsens.','Both VTEPs show the approved VNI and bidirectional tenant traffic succeeds. ',False,'',['CLOUDOPS']))
    add(11,'Patch:CONTRADICTORY_PATH','Synthetic probes show loss through one transit, but interface counters are clean and a simultaneous packet capture shows complete delivery. Monitoring timestamps are unsynchronized.',response('Network','Routing','INSUFFICIENT_EVIDENCE: contradictory observations may be caused by time alignment or probe behavior.',['Probe reports loss','Counters are clean','Capture shows delivery','Timestamps differ'],[hyp('Transient path loss','SUSPECTED',['probe result']),hyp('Monitoring time skew','SUSPECTED',['unsynchronized timestamps'])],['synchronized probe and capture','device clock state','per-hop telemetry'],'Repeat tests with synchronized clocks','Path telemetry',EMPTY,'Do not reroute or change policy until synchronized evidence identifies loss.','An unnecessary route change can shift production traffic.','No rollback is needed for synchronized diagnostics.','Reconcile probe, capture, and counters on one timeline. ',True,'Contradictory evidence cannot establish RCA. ',[]))
    add(12,'Patch:CLOUD_SECURITY_AMBIGUOUS','A cloud-hosted API became unreachable after a release. No route table diff, security policy log, load-balancer health, or application listener evidence is available.',response('Network','Cloud Connectivity','INSUFFICIENT_EVIDENCE: network, cloud policy, load balancer, and application causes remain viable.',['API unreachable after release'],[hyp('Cloud security policy block','SUSPECTED',[]),hyp('Route change','SUSPECTED',[]),hyp('Application listener failure','SUSPECTED',[])],['flow logs','route diff','security policy decision','listener health'],'Collect cloud and application evidence on one failed flow','Cloud flow logs',EMPTY,'Do not change routes or security policy from the release correlation alone.','Blind policy changes may expose or disrupt services.','No rollback is required for evidence collection.','Locate the failed hop and correlate with release changes. ',True,'A timing correlation is not causal proof.',['CLOUDOPS','MIDDLEWARE']))
    add(13,'Patch:SECURITY_BLOCK_AMBIGUOUS','One client reports a reset when accessing a protected service. Firewall decisions, endpoint security events, server logs, and packet direction are unavailable.',response('Network','Security Connectivity','INSUFFICIENT_EVIDENCE: reset origin and policy decision are unknown.',['One client receives a reset'],[hyp('Firewall rejection','SUSPECTED',[]),hyp('Endpoint security reset','SUSPECTED',[]),hyp('Server reset','SUSPECTED',[])],['bidirectional packet capture','firewall decision log','endpoint event','server connection log'],'Identify which device originated the reset','Packet capture',EMPTY,'Do not relax firewall policy without a correlated deny decision.','Unverified policy relaxation creates security exposure.','No rollback is required for read-only diagnostics.','Attribute the reset source and correlate it with policy and service logs. ',True,'Reset alone does not identify the responsible domain.',['CYBER']), 'validation')
    add(14,'Patch:BGP_SUPPORTED','A prefix disappears intermittently. Both route reflectors log withdrawals from the same peer, while IGP reachability to the peer remains stable and no local policy change exists.',response('Network','BGP','Peer-originated withdrawals are SUPPORTED; the remote cause is not yet confirmed.',['Both reflectors observe same withdrawal','IGP to peer stable','No local policy change'],[hyp('Remote peer is withdrawing the prefix','SUPPORTED',['matching withdrawal logs'])],['remote peer advertisement and event log'],'Request remote peer evidence before remediation','BGP logs',EMPTY,'Keep local configuration unchanged and escalate to the peer owner.','Resetting a healthy session may increase churn.','No rollback is required for read-only validation.','Correlate remote advertisement state with local withdrawal timestamps. ',False,'',['NETWORK_PEER_OWNER']), 'validation')
    add(15,'Patch:NETWORK_ELIMINATED_APP','Users see slow transactions, but packet capture shows no loss or retransmission, RTT is stable, and application traces show 12-second processing inside one service.',response('Network','Connectivity','Network transport is ELIMINATED by clean packet and latency evidence; delay is inside the application service.',['No loss or retransmission','Stable RTT','Application processing is 12 seconds'],[hyp('Network transport degradation','ELIMINATED',['clean capture','stable RTT']),hyp('Application processing delay','SUPPORTED',['application trace'])],['service internal timing breakdown'],'Escalate the trace to Middleware for service diagnosis','Packet capture and application trace',EMPTY,'No network remediation; investigate service processing.','Unnecessary network changes add outage risk.','No rollback is needed because no change is proposed.','Middleware confirms the slow processing stage while network metrics remain healthy. ',False,'',['MIDDLEWARE']), 'validation')
    add(16,'Patch:DUAL_HYPOTHESIS_AMBIGUOUS','Voice quality degrades for a remote office. WAN loss telemetry is absent, Wi-Fi retries are unknown, and call-server jitter reports are unavailable.',response('Network','Voice Connectivity','INSUFFICIENT_EVIDENCE: WAN, wireless, and voice-service hypotheses remain viable.',['Remote office voice quality degradation'],[hyp('WAN loss or jitter','SUSPECTED',[]),hyp('Wireless retries','SUSPECTED',[]),hyp('Voice service jitter','SUSPECTED',[])],['WAN loss and jitter','wireless retry rate','call-server RTP statistics'],'Collect time-aligned WAN, wireless, and RTP evidence','Network and voice telemetry',EMPTY,'Do not change QoS, RF, or routing policy without discriminating evidence.','Unverified changes can degrade other traffic.','No rollback is needed for read-only evidence collection.','Correlate a single call across WAN, wireless, and RTP timelines. ',True,'Multiple domains remain plausible.',['MIDDLEWARE']), 'validation')
    return rows

def main():
    from transformers import AutoTokenizer
    train=read(V6/'train.jsonl'); val=read(V6/'validation.jsonl'); original=train+val
    patches=patch_rows(); train2=train+[x for x in patches if x['provenance']['splitIntent']=='train']; val2=val+[x for x in patches if x['provenance']['splitIntent']=='validation']
    V7.mkdir(parents=True,exist_ok=True)
    for name,rows in [('train.jsonl',train2),('validation.jsonl',val2)]: (V7/name).write_text(''.join(json.dumps(x,ensure_ascii=False)+'\n' for x in rows),encoding='utf-8')
    allrows=train2+val2; prompts=[x['messages'][1]['content'] for x in allrows]; answers=[x['messages'][-1]['content'] for x in allrows]
    families_train={x['provenance']['incidentFamily'] for x in train2}; families_val={x['provenance']['incidentFamily'] for x in val2}
    benchmark=[]
    for p in BENCH.rglob('*.jsonl'): benchmark += read(p)
    leak=[]
    for row in patches:
        source=(row['messages'][1]['content']+' '+row['messages'][-1]['content']).lower()
        for case in benchmark:
            target=(case['id']+' '+case['scenario']).lower()
            if case['id'].lower() in source or case['scenario'].lower() in source or SequenceMatcher(None,source,target).ratio()>=.72: leak.append({'patch':row['provenance']['incidentId'],'benchmark':case['id']})
    near=[]
    for i in range(len(answers)):
        for j in range(i+1,len(answers)):
            ratio=SequenceMatcher(None,answers[i],answers[j]).ratio()
            if ratio>=.92: near.append({'a':i+1,'b':j+1,'ratio':round(ratio,4)})
    tok=AutoTokenizer.from_pretrained(MODEL,revision=REV,trust_remote_code=False); lengths=[len(tok.apply_chat_template(x['messages'],tokenize=True,add_generation_prompt=False,enable_thinking=False)) for x in allrows]
    sorted_l=sorted(lengths); q=lambda p:sorted_l[min(len(sorted_l)-1,math.ceil(len(sorted_l)*p)-1)]
    schemas=[]
    required={'domain','technology','vendor','assessment','observedFacts','hypotheses','missingEvidence','nextDiagnosticAction','toolSelection','rootCause','remediation','risk','rollback','verification','abstain','abstentionReason','escalateTo'}
    for row in patches:
        a=assistant(row)
        if set(a)!=required: schemas.append({'id':row['provenance']['incidentId'],'missing':sorted(required-set(a)),'extra':sorted(set(a)-required)})
    report={'sourceAudit':{'train':audit(train),'validation':audit(val),'all':audit(original)},'patchCount':len(patches),'total':len(allrows),'train':len(train2),'validation':len(val2),'exactDuplicatePrompts':len(prompts)-len(set(prompts)),'exactDuplicateResponses':len(answers)-len(set(answers)),'nearDuplicatePairsAt092':near,'familyLeakage':sorted(families_train&families_val),'benchmarkLeakage':leak,'patchSchemaErrors':schemas,'tokenStats':{'p50':q(.5),'p90':q(.9),'p95':q(.95),'p99':q(.99),'max':max(lengths),'over512':sum(x>512 for x in lengths)},'baseModel':MODEL,'revision':REV}
    gates=not any((report['exactDuplicatePrompts'],report['exactDuplicateResponses'],near,report['familyLeakage'],leak,schemas,report['tokenStats']['over512']))
    report['gatesPassed']=gates; (V7/'quality-report.json').write_text(json.dumps(report,indent=2),encoding='utf-8')
    readiness={'experimentReadiness':'EXPERIMENT_READY_NOT_SME_APPROVED' if gates else 'BLOCKED','readyForPilotTraining':gates,'baseModel':MODEL,'revision':REV,'maxSequenceLength':512,'trainCount':len(train2),'validationCount':len(val2),'sha256':{n:hashlib.sha256((V7/n).read_bytes()).hexdigest() for n in ('train.jsonl','validation.jsonl')}}
    (V7/'readiness.json').write_text(json.dumps(readiness,indent=2),encoding='utf-8'); print(json.dumps({'gatesPassed':gates,**report},indent=2))
if __name__=='__main__': main()
