"""Generate 20 transparent synthetic DHCP supervision cases for the demo pilot."""
import argparse, json
from pathlib import Path

FAMILIES = [
 ("WINDOWS_LONG_LEASE", "Windows DHCP", "Get-DhcpServerv4ScopeStatistics -ComputerName dhcp01 -ScopeId 10.220.0.0", "Get-DhcpServerv4Lease -ComputerName dhcp01 -ScopeId 10.220.0.0 | Group-Object AddressState", "Scope utilization is 99%; leases from transient clients remain active for eight days.", "Lease duration is oversized for the observed client churn, exhausting usable addresses.", "Authorize a bounded scope extension or remove only leases proven stale after ownership checks.", "Right-size the lease duration and scope using measured peak concurrency; alert at 80% and 90% utilization."),
 ("WINDOWS_BAD_ADDRESS", "Windows DHCP", "Get-DhcpServerv4Lease -ComputerName dhcp01 -ScopeId 10.221.0.0 -AddressState BadAddress", "Get-WinEvent -LogName Microsoft-Windows-DHCP-Server/Operational -MaxEvents 100", "The scope contains repeated BAD_ADDRESS leases and DHCP conflict events for the same access segment.", "Duplicate static addressing inside the pool causes conflict detection to quarantine addresses.", "Find the conflicting endpoints before deleting their verified BAD_ADDRESS entries; validate one test lease.", "Move static addresses outside the pool, correct IPAM ownership, and monitor conflict-event recurrence."),
 ("FAILOVER_STATE", "Windows DHCP failover", "Get-DhcpServerv4Failover -ComputerName dhcp01 | Format-List *", "Get-DhcpServerv4ScopeStatistics -ComputerName dhcp02 -ScopeId 10.222.0.0 -Failover", "Partners report COMMUNICATIONS-INTERRUPTED and inconsistent free-address counts beyond the configured MCLT.", "Failover state and lease ownership are not synchronized, preventing safe reuse of partner-owned leases.", "Restore partner communication and reconcile state; do not force partner-down until impact and MCLT are reviewed.", "Repair failover connectivity and time synchronization, test replication, and alert on state divergence."),
 ("INFOBLOX_HA", "Infoblox NIOS", "show dhcp_gss_statistics", "Infoblox API: GET /wapi/v2.12/lease?_return_fields=address,binding_state,ends", "The serving Grid member is degraded and lease updates are queued while its HA peer is not taking service.", "A degraded NIOS DHCP member and failed HA transition leave lease state stale and reduce available capacity.", "Follow the approved NIOS HA runbook to restore or fail over the member, then verify new leases from a test client.", "Correct HA health and Grid replication, validate capacity, and add member-state and allocation alarms."),
 ("KEA_RECLAIM", "Linux Kea DHCP", "kea-shell --host 127.0.0.1 --port 8000 lease4-get-all", "journalctl -u kea-dhcp4 --since '-30 min' --no-pager", "Expired-reclamation logs show database timeouts and leases remain expired-reclaimed=false past the configured cleanup interval.", "Kea cannot complete expired-lease reclamation because the lease database is timing out.", "Restore database availability and run the documented bounded reclamation operation; verify allocation and rollback readiness.", "Fix database latency, tune reclamation timers from measured load, monitor reclamation failures, and test HA recovery."),
]

def rows():
    sites=["Mumbai","London","Chicago","Singapore"]
    for family,platform,check1,check2,evidence,cause,temp,permanent in FAMILIES:
        for variant,site in enumerate(sites,1):
            incident=f"SIM-DHCP-{family}-{variant:02d}"
            prompt=f"{site} clients cannot obtain DHCP addresses; existing clients remain connected. Diagnose the {family.lower().replace('_',' ')} condition on {platform} using the supplied evidence and give temporary and permanent fixes."
            answer={"issueSummary":f"New clients at {site} cannot obtain a lease while existing leased clients remain online.","evidence":[evidence],"validationChecks":[check1,check2],"rejectedHypothesis":"A relay or VLAN failure is not established without gateway and helper-path evidence.","rootCause":cause,"temporaryFix":temp,"permanentFix":permanent,"verification":"Renew one authorized test client, confirm the expected scope and gateway, then compare free-address count and error events.","rollback":"Reverse the bounded change and restore the exported configuration or lease data if allocation or reachability regresses.","confidence":0.92,"dataOrigin":"SIMULATION"}
            yield {"trainingReady":True,"messages":[{"role":"system","content":"You are a senior infrastructure engineer. Use only supplied evidence, select platform-specific read-only checks, distinguish hypotheses from facts, and include approval, rollback, and verification. Return compact JSON; never claim simulated evidence is live."},{"role":"user","content":prompt},{"role":"assistant","content":json.dumps(answer,separators=(',',':'))}],"provenance":{"domain":"NETWORK","incidentId":incident,"incidentFamily":"DHCP:"+family,"mode":"SIMULATION","source":"CURATED_SYNTHETIC_DEMO","curationType":"USER_AUTHORIZED_SYNTHETIC","reviewerId":"DEMO-CURRICULUM-AUTHORIZATION","reviewEventId":"CURATE-"+incident},"reviewNotice":"Synthetic demo supervision authorized for the local pilot; it is not production evidence or a human incident review."}

def main():
    p=argparse.ArgumentParser(); p.add_argument('--output',type=Path,required=True); args=p.parse_args()
    data=list(rows()); args.output.parent.mkdir(parents=True,exist_ok=True); args.output.write_text(''.join(json.dumps(x,ensure_ascii=False)+'\n' for x in data),encoding='utf-8')
    print(json.dumps({'created':len(data),'families':len({x['provenance']['incidentFamily'] for x in data}),'mode':'SIMULATION','trainingClaim':False}))
if __name__=='__main__': main()
