"""Generate auditable synthetic senior-engineer cases for non-network twin pilots."""
import argparse, json
from pathlib import Path

CURRICULA = {
"WINDOWS": [
 ("AD_REPLICATION","Active Directory replication and authentication degradation",["repadmin /replsummary","dcdiag /test:Advertising /test:DNS /v"],"Replication failures and DNS registration errors begin after one domain controller loses site connectivity.","A domain controller site path failure prevents replication and causes clients to select stale directory data.","Keep affected clients on a verified healthy domain controller and restore the site path through approval.","Monitor replication age, DNS registration, site links, time synchronization, and authentication probes."),
 ("KERBEROS_TIME","Kerberos authentication failures",["w32tm /query /status","klist"],"The affected host clock exceeds the domain tolerance while DNS and TCP reachability to a KDC are healthy.","Host time drift invalidates Kerberos ticket validation.","Restore the approved time source, resynchronize, and retest one authorized identity.","Enforce redundant trusted time sources and alert before authentication tolerance is exceeded."),
 ("DHCP_EXHAUSTION","DHCP clients receive no address",["Get-DhcpServerv4ScopeStatistics","Get-DhcpServerv4Failover"],"The target scope has no free addresses; failover is healthy and relay requests reach the server.","The scope is exhausted by valid and long-lived leases.","Authorize a bounded scope extension or remove only leases proven stale.","Right-size address capacity and lease duration from measured concurrency and churn."),
 ("GPO_FAILURE","Group Policy does not apply",["gpresult /h gp-report.html","Get-WinEvent -FilterHashtable @{LogName='System'; StartTime=(Get-Date).AddMinutes(-30)} -MaxEvents 100"],"The computer is in the expected OU but SYSVOL access fails only through one domain controller.","A domain-controller SYSVOL or replication fault prevents policy retrieval.","Use a verified healthy domain controller while the failed replication path is repaired.","Monitor SYSVOL health, replication, DNS, and representative policy application."),
 ("IIS_DEPENDENCY","IIS application returns 503",["Get-WebAppPoolState","Get-WinEvent -FilterHashtable @{LogName='System'; StartTime=(Get-Date).AddMinutes(-30)} -MaxEvents 100"],"The application pool stops after repeated identity logon failures while HTTP.sys remains available.","The application-pool service identity can no longer authenticate after a credential lifecycle change.","Restore the approved credential binding and start the pool after owner approval.","Use managed identities where supported and validate credential rotation before expiry."),
],
"LINUX": [
 ("SYSTEMD_DEPENDENCY","service fails during startup",["systemctl status app.service --no-pager","journalctl -u app.service --since '-30 min' --no-pager"],"The unit fails after its required mount times out; CPU, memory, and network remain healthy.","A required mount dependency is unavailable during unit startup.","Restore the mount or use an approved degraded-mode dependency before restarting.","Correct unit ordering and mount resilience, then test cold-start recovery."),
 ("DNS_RESOLUTION","Linux dependency lookup fails",["resolvectl status","getent ahosts service.example"],"The host uses an obsolete resolver pushed by a stale network profile while direct authoritative queries succeed.","A stale resolver configuration sends queries to a retired DNS server.","Apply the approved resolver profile and re-test the exact service name.","Manage resolver intent centrally and alert on drift and lookup failure."),
 ("FILESYSTEM_FULL","application writes fail",["df -h","df -i"],"The data filesystem has free bytes but no free inodes because millions of expired small files remain.","Inode exhaustion prevents new files despite apparent byte capacity.","Remove only retention-expired files under approval and confirm inode recovery.","Enforce retention, inode monitoring, and workload-specific filesystem sizing."),
 ("MEMORY_PRESSURE","processes are killed",["free -m","journalctl -k --since '-30 min' --no-pager"],"Kernel logs identify the workload as an OOM victim after its memory use crosses the cgroup limit.","A workload memory regression exceeds its configured cgroup limit.","Roll back the verified workload revision or temporarily adjust the reviewed limit.","Fix memory growth, load-test limits, and alert on working-set slope and OOM events."),
 ("NETWORK_ROUTE","service cannot reach one subnet",["ip route get 192.0.2.10","ip rule"],"Policy routing selects an obsolete table only for the application source address.","A stale policy-routing rule sends application traffic to an invalid next hop.","Use the verified main route after a reviewed policy-rule correction.","Manage policy routing as versioned intent and test source-specific reachability."),
],
"SECURITY": [
 ("IDENTITY_COMPROMISE","suspicious privileged sign-ins",["Query identity sign-in risk and MFA events for the UTC window","Correlate source IP, device identity, token, and administrator change records"],"Impossible-travel and MFA fatigue indicators align with an unapproved privileged sign-in and subsequent role change.","A privileged identity was likely compromised through successful MFA fatigue.","Revoke active sessions and contain the identity after incident-command approval while preserving evidence.","Deploy phishing-resistant MFA, privileged access workflows, and high-risk sign-in controls."),
 ("RANSOMWARE_SIGNAL","endpoint mass file changes",["Collect EDR process tree and file-event timeline","Correlate identity, SMB, backup, and network telemetry"],"Unsigned encryption activity, recovery inhibition, and rapid file renames share one process ancestry.","Malicious execution is encrypting accessible data and inhibiting recovery.","Isolate affected endpoints and identities through emergency approval and protect clean backups.","Eradicate persistence, close entry vector, restore clean data, and validate detections."),
 ("CLOUD_KEY_ABUSE","cloud API activity from leaked key",["Query provider audit logs by access key and request ID","Compare source, user agent, permissions, and approved automation runs"],"A long-lived key performs discovery and creates credentials from an unrecognized source outside change windows.","A cloud access key is compromised and used for unauthorized persistence.","Disable the key and contain created credentials after approval while retaining audit evidence.","Replace long-lived keys with workload identity and enforce least privilege and anomaly detection."),
 ("FIREWALL_CHANGE","unexpected exposure after policy change",["Compare effective rule and approved change revision","Correlate flow logs, asset exposure, and vulnerability evidence"],"A broad allow rule precedes the intended scoped rule and exposes an administrative service.","Firewall rule ordering introduced unintended external access.","Disable or narrow the exact rule through emergency change approval.","Add policy regression tests, expiry, peer review, and continuous exposure validation."),
 ("PHISHING","suspected phishing campaign",["Collect message trace, headers, URLs, attachments, and recipient actions","Correlate endpoint, identity, DNS, and proxy telemetry"],"Multiple recipients received an impersonation domain and one browser session submitted credentials before a risky sign-in.","A phishing campaign captured at least one user's credentials.","Block indicators, contain affected sessions, and notify impacted users through approved response.","Strengthen mail authentication, phishing-resistant MFA, detections, and awareness using verified campaign traits."),
],
"DEVOPS": [
 ("ROLLOUT_READINESS","Kubernetes rollout stalls",["kubectl get deployment,pods -n app -o wide","kubectl get events -n app --sort-by=.metadata.creationTimestamp"],"New pods fail readiness on a dependency endpoint while the prior ReplicaSet remains ready.","The release references an unavailable dependency endpoint.","Pause rollout and return traffic to the verified prior ReplicaSet after approval.","Validate dependencies in pre-production and gate rollout on representative readiness checks."),
 ("IMAGE_PULL","pods cannot pull image",["kubectl describe pod app-0 -n app","kubectl get serviceaccount app -n app -o yaml"],"Events show authorization denied for the exact digest after registry permissions changed.","The workload identity lost pull permission for the release repository.","Restore least-privilege pull access to the specific repository under approval.","Test workload identity and immutable digest access before deployment."),
 ("PIPELINE_SECRET","deployment pipeline authentication fails",["Inspect failed stage metadata with secret values redacted","Compare credential reference, scope, expiry, and last successful run"],"The credential reference points to a rotated version the runner cannot access.","Credential rotation did not update runner access to the new secret version.","Restore runner access to the approved version without exposing the secret.","Use workload identity and rotation tests with audited secret-version transitions."),
 ("CONFIG_DRIFT","runtime differs from release intent",["kubectl diff -f approved-release.yaml","kubectl rollout history deployment/app -n app"],"A manual environment change altered a feature flag outside GitOps and precedes the errors.","Unreviewed runtime configuration drift enabled an incompatible feature path.","Reconcile to the last approved configuration after change approval.","Enforce GitOps ownership, drift alerts, admission policy, and configuration integration tests."),
 ("DATABASE_MIGRATION","release fails after schema migration",["Compare migration version with application revision","Inspect migration job and database lock evidence"],"The new application expects a column that the blocked migration never committed.","A blocked schema migration left application and database versions incompatible.","Route traffic to the compatible revision and resolve the blocker under DBA approval.","Use backward-compatible expand-contract migrations and deployment gates."),
],
"CLOUDOPS": [
 ("LOAD_BALANCER","cloud load balancer targets unhealthy",["Inspect target health reason codes","Correlate health probes, NSG rules, application readiness, and changes"],"Targets are ready locally but health probes are denied by a newly scoped network rule.","A network security rule blocks the load-balancer health probe source.","Restore only the documented probe path after security approval.","Test health-probe reachability in policy CI and monitor target reason codes."),
 ("HYBRID_ROUTE","hybrid cloud path is asymmetric",["Inspect effective routes and next hop","Compare cloud gateway and on-premises BGP routes in the same UTC window"],"A more-specific cloud route sends return traffic through a different firewall than the forward path.","Route specificity creates an asymmetric stateful-firewall path.","Withdraw the erroneous route through joint Network and CloudOps approval.","Validate bidirectional path intent and route precedence before deployment."),
 ("IAM_DENIAL","automation receives access denied",["Inspect audit event principal, action, resource, and denial context","Evaluate effective identity and resource policies"],"A permissions boundary denies one required read action although the role policy allows it.","The permissions boundary omits the required scoped read operation.","Add only the validated read action after owner and security approval.","Test effective permissions for representative operations in delivery pipelines."),
 ("QUOTA_EXHAUSTION","autoscaling cannot add capacity",["Inspect scaling activities and failure reason","Compare regional quota, requested capacity, demand, and instance availability"],"Scaling requests fail at a regional quota while existing instances are saturated.","Regional service quota exhaustion prevents the autoscaler from meeting demand.","Shift bounded load or request approved quota while protecting service limits.","Forecast quota headroom and validate alternate-zone or regional capacity."),
 ("COST_ANOMALY","unexpected cloud cost increase",["Break down cost by account, region, service, resource, and tag","Correlate usage, deployment, scaling, and pricing changes"],"Unbounded debug-log ingestion begins with a release and accounts for the increase.","A release enabled high-volume debug logging without retention safeguards.","Restore approved log level and retention after preserving incident evidence.","Enforce telemetry budgets, retention policy, anomaly alerts, and release checks."),
]}

SITES=["Mumbai","London","Chicago","Singapore"]
def build(domain):
 for family,title,checks,evidence,cause,temp,permanent in CURRICULA[domain]:
  for n,site in enumerate(SITES,1):
   incident=f"SIM-MASTERY-{domain}-{family}-{n:02d}"
   answer={"issueSummary":f"{site}: {title}.","rankedHypotheses":[{"hypothesis":cause,"status":"SUPPORTED"},{"hypothesis":"A neighboring domain is the sole cause.","status":"NOT_PROVEN"}],"evidence":[evidence],"validationChecks":checks,"reasoningSummary":"The listed observation discriminates the supported cause from broader availability and dependency hypotheses; current state still requires target-bound verification.","rootCause":cause,"temporaryFix":temp,"permanentFix":permanent,"crossTwinChecks":["Share the incident ID, UTC window, target, exact observations and limitations with the dependency owner."],"verification":"Repeat the affected transaction and compare fresh service, dependency and user-impact telemetry with the baseline.","rollback":"Restore the versioned prior state if success criteria fail or impact expands.","escalation":"Require human approval for mutation; escalate with evidence IDs when ownership or vendor behavior remains inconclusive.","confidence":0.91,"dataOrigin":"SIMULATION"}
   yield {"trainingReady":True,"messages":[{"role":"system","content":f"Act as a senior {domain} engineer. Produce auditable reasoning summaries, not hidden chain-of-thought. Rank hypotheses, use evidence-specific read-only checks, correlate twins, abstain when proof is missing, and include approval, rollback and verification. Return compact JSON and label simulation."},{"role":"user","content":f"Investigate this {domain} incident in {site}: {title}. Use the supplied observation and produce an evidence-led response."},{"role":"assistant","content":json.dumps(answer,separators=(',',':'))}],"provenance":{"domain":domain,"specialty":f"{domain}-MASTERY","incidentId":incident,"incidentFamily":f"{domain}:{family}","mode":"SIMULATION","source":"CURATED_SYNTHETIC_DEMO","curationType":"USER_AUTHORIZED_SYNTHETIC","reviewerId":"DEMO-CURRICULUM-AUTHORIZATION","reviewEventId":"CURATE-"+incident},"reviewNotice":"Synthetic demo supervision; benchmark and domain review are required before promotion."}

def main():
 p=argparse.ArgumentParser();p.add_argument('--domain',choices=CURRICULA,required=True);p.add_argument('--output',type=Path,required=True);a=p.parse_args();rows=list(build(a.domain));a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(''.join(json.dumps(r,ensure_ascii=False)+'\n' for r in rows),encoding='utf-8');print(json.dumps({'domain':a.domain,'created':len(rows),'families':5}))
if __name__=='__main__': main()
