"""Generate 20 transparent synthetic cases for one network-engineering specialty."""
import argparse, json
from pathlib import Path

CURRICULA = {
"routing-switching":[
 ("VLAN_TRUNK","Cisco IOS XE","show interfaces trunk","show interfaces switchport","The access VLAN is 230 while the approved endpoint VLAN is 220; the uplink permits both.","An access-port VLAN change placed clients in the wrong broadcast domain.","Restore VLAN 220 on the affected access port after approval.","Add intent validation and pre/post-change endpoint reachability checks."),
 ("BGP_POLICY","Cisco IOS XE","show bgp ipv4 unicast summary","show bgp ipv4 unicast neighbors 192.0.2.1 received-routes","The preferred prefix is received but a new local-preference policy selects the higher-latency transit path.","A route-policy change altered BGP best-path selection.","Rollback the exact route-map revision and soft-refresh the affected neighbor.","Peer-review routing policy and test path selection against a route-policy fixture."),
 ("OSPF_ADJACENCY","Cisco IOS XE","show ip ospf neighbor detail","show ip ospf interface GigabitEthernet0/1","Peers remain EXSTART and report different interface MTU values.","An OSPF interface MTU mismatch prevents database-description exchange.","Restore the approved interface MTU consistently on both peers.","Enforce routed-link MTU intent and verify adjacency plus route installation after changes."),
 ("STP_LOOP","Cisco Catalyst","show spanning-tree vlan 220 detail","show interfaces counters errors","Root changes and topology notifications correlate with a newly connected unapproved trunk.","The added trunk created a Layer-2 loop and repeated STP convergence.","Isolate the identified link after approval and confirm the intended root path.","Apply BPDU Guard/Root Guard by port role and validate topology before activation."),
 ("PORT_CHANNEL","Cisco Catalyst","show etherchannel summary","show interfaces port-channel 10","One member is suspended because its LACP mode and allowed VLAN list differ from the bundle.","EtherChannel member configuration drift reduced capacity and caused asymmetric forwarding.","Align the suspended member with the approved bundle template.","Use atomic port-channel templates and alarm on suspended or individual members."),
],
"palo-alto":[
 ("SECURITY_POLICY","Palo Alto PAN-OS","show running security-policy","test security-policy-match from trust to untrust source 192.0.2.10 destination 198.51.100.20 protocol 6 destination-port 443","Traffic logs show interzone-default deny after the application moved zones.","The intended application no longer matches the scoped security rule after a zone change.","Add the validated zone to the existing least-privilege rule through a reviewed commit.","Bind policy tests to application, zones, ports and approved change records."),
 ("NAT_POLICY","Palo Alto PAN-OS","show running nat-policy","test nat-policy-match from trust source 192.0.2.10 to untrust destination 198.51.100.20 protocol 6 destination-port 443","The translated source pool is exhausted while sessions continue matching the intended NAT rule.","The dynamic IP NAT pool lacks capacity for concurrent sessions.","Use the approved overflow pool or reduce verified stale sessions under change control.","Right-size translated capacity and alert on pool/session utilization."),
 ("IPSEC_TUNNEL","Palo Alto PAN-OS","show vpn ike-sa gateway branch-gw","show vpn ipsec-sa tunnel branch-tunnel","IKE is established but IPSec counters show proxy-ID mismatch and no decapsulation.","Mismatched traffic selectors prevent the data-plane security association from carrying traffic.","Restore matching approved proxy IDs on both peers.","Manage selectors as shared intent and verify encrypt/decrypt counters after change."),
 ("DECRYPTION_CERT","Palo Alto PAN-OS","show system setting ssl-decrypt certificate","show log system direction equal backward subtype equal sslmgr","The forward-trust certificate is expired and affected clients reject the replacement chain.","An expired decryption trust certificate breaks inspected TLS sessions.","Use the approved renewed trust certificate and validate a scoped test population.","Automate expiry monitoring, staged trust distribution and rollback validation."),
 ("HA_STATE","Palo Alto PAN-OS","show high-availability state","show high-availability all","HA2 is down and session synchronization is incomplete although HA1 remains healthy.","The HA2 data link failure prevents session-state replication.","Restore the HA2 path before any controlled failover.","Provide redundant HA links and alarm on synchronization health and link state."),
],
"cisco-ise":[
 ("DOT1X_CERT","Cisco ISE","show application status ise","show logging application ise-psc.log tail","RADIUS Live Logs show EAP-TLS failure because the endpoint certificate chain is untrusted.","The issuing CA is missing from the applicable ISE trusted-certificate store.","Import and scope the validated CA chain through approved certificate change control.","Monitor trust-chain expiry and test EAP-TLS against staged policy nodes."),
 ("MAB_PROFILE","Cisco ISE","show logging application profiler.log tail","show logging application prrt-server.log tail","The endpoint is classified as Unknown and the authorization policy requires the expected printer profile.","Missing profiling attributes prevent the MAB endpoint from matching its authorization rule.","Collect approved probes or apply a temporary endpoint identity group after ownership validation.","Improve profiling probes and maintain governed static classifications with expiry."),
 ("PSN_LATENCY","Cisco ISE","show application status ise","show logging application radius.log tail","Network devices report RADIUS timeouts to one PSN while another PSN responds normally.","A degraded Policy Service Node causes authentication latency and retransmissions.","Remove the unhealthy PSN from the NAD server group after approval.","Repair PSN resource health and use load-balanced health-aware RADIUS configuration."),
 ("AD_JOIN","Cisco ISE","show logging application ad_agent.log tail","show ntp","Join diagnostics show Kerberos clock-skew errors and NTP offset beyond policy.","Time drift prevents ISE from authenticating reliably to Active Directory.","Restore approved NTP synchronization and re-test the join without resetting credentials.","Use redundant trusted time sources and alert before Kerberos skew limits."),
 ("POLICY_ORDER","Cisco ISE","show logging application prrt-server.log tail","show logging application ise-psc.log tail","Live Logs show a broad deny authorization rule matching before the intended compliant-device rule.","Authorization rule ordering shadows the intended policy.","Move the specific validated rule above the broad deny through reviewed policy deployment.","Add policy-set regression tests for representative endpoint attributes."),
],
"wireless":[
 ("CAPWAP_JOIN","Cisco Catalyst 9800 WLC","show wireless stats ap join summary","show logging profile wireless start last 30 minutes filter mac 00:11:22:33:44:55","The AP reaches discovery but DTLS establishment fails after controller certificate expiry.","An expired controller trust certificate prevents the AP CAPWAP DTLS join.","Install the approved renewed certificate and validate one staged AP join.","Monitor certificate lifetime and stage AP/controller trust before renewal."),
 ("RF_INTERFERENCE","Cisco Catalyst 9800 WLC","show wireless stats ap radio summary","show ap dot11 5ghz cleanair device type all","Channel utilization and non-Wi-Fi interference are high on one floor while wired uplinks are healthy.","Persistent non-Wi-Fi interference reduces usable airtime.","Use reviewed RRM channel changes or remove the identified interferer and remeasure airtime.","Perform spectrum surveys, tune RRM bounds and alert on sustained channel utilization."),
 ("ROAMING","Cisco Catalyst 9800 WLC","show wireless client mac-address 00:11:22:33:44:55 detail","show wlan name Corp-Secure","Roam failures occur between AP groups where 802.11r and key-management settings differ.","Inconsistent WLAN fast-transition configuration breaks roaming authentication.","Align the affected AP group's WLAN policy after compatibility review.","Apply one versioned WLAN policy and test roaming with representative clients."),
 ("WLAN_VLAN","Cisco Catalyst 9800 WLC","show wireless client mac-address 00:11:22:33:44:55 detail","show wireless vlan details","Clients associate successfully but receive no DHCP offer; the policy profile maps to VLAN 230 instead of 220.","The WLAN policy profile maps clients to the wrong DHCP broadcast domain.","Restore VLAN 220 mapping and verify a test lease plus gateway reachability.","Validate WLAN-to-VLAN intent and DHCP relay reachability before deployment."),
 ("AP_UPLINK","Cisco Catalyst 9800 WLC","show ap name branch-ap-01 config general","show ap name branch-ap-01 ethernet statistics","AP Ethernet errors and negotiated 100 Mbps speed correlate with user throughput degradation.","A degraded AP switchport/cabling path constrains capacity and introduces loss.","Move the AP to a verified cable and port after change approval.","Certify cabling, enforce expected speed/duplex and monitor AP uplink errors."),
],
"sdwan-zscaler":[
 ("CONTROL_CONNECTION","Cisco Catalyst SD-WAN","show sdwan control connections","show sdwan certificate installed","The edge has underlay reachability but its controller sessions fail while certificate validity and clock evidence are outside the approved baseline.","Certificate or time validation prevents the SD-WAN edge from establishing authenticated controller connections.","Keep traffic on the verified backup transport while the certificate and time owner validates the edge.","Renew certificates before expiry, use redundant trusted NTP, and alert on control-session loss."),
 ("BFD_UNDERLAY","Cisco Catalyst SD-WAN","show sdwan bfd sessions","show sdwan tunnel statistics","BFD loss and tunnel drops affect one transport color while controller connections remain established.","Loss or MTU impairment on the selected underlay path destabilizes the SD-WAN data-plane tunnel.","Steer the affected application class to a healthy color after approval and preserve failing-path counters.","Correct carrier loss or MTU, then verify BFD stability, tunnel counters, and application probes."),
 ("APP_ROUTE_SLA","Cisco Catalyst SD-WAN","show sdwan app-route stats","show sdwan policy from-vsmart","The ZIA application class remains on a path whose latency exceeds the centralized SLA threshold because the intended policy is not active on the edge.","Missing or stale centralized app-route policy prevents SLA-aware path selection.","Use the already validated healthy transport through an approved traffic-policy change.","Repair policy distribution, add policy-version drift detection, and test SLA failover before rollout."),
 ("ZIA_GRE_LATENCY","Cisco SD-WAN with Zscaler ZIA","show sdwan app-route stats","show sdwan bfd sessions","Branch underlay is healthy, but browser-to-ZIA performance testing shows elevated service-edge latency and both GRE paths resolve to the same impaired service-edge region.","The selected ZIA service edge is adding latency after the SD-WAN underlay, rather than a LAN or Windows fault.","Fail over to the validated secondary ZIA tunnel or service edge after approval.","Use diverse primary and backup ZIA tunnels, monitor service reachability beyond GRE state, and enforce latency-based steering."),
 ("ZIA_FORWARDING_CAPACITY","Cisco SD-WAN with Zscaler ZIA","show sdwan tunnel statistics","show sdwan app-route stats","The active GRE forwarding path approaches its engineered capacity during peak hours while loss begins only for ZIA-bound traffic.","ZIA forwarding concentration on one tunnel creates a capacity bottleneck despite available WAN bandwidth.","Distribute validated traffic across healthy provisioned tunnels under change control.","Capacity-plan per forwarding tunnel, preserve flow persistence, and alert before sustained saturation."),
],
"silverpeak-edgeconnect":[
 ("TUNNEL_DOWN","HPE Aruba Networking EdgeConnect (formerly Silver Peak)","show interfaces tunnel summary","show interfaces tunnel <tunnel-name> ipsec status","The affected overlay tunnel is down while the WAN interface and peer reachability remain available; IPSec status identifies failed negotiation for that tunnel.","Tunnel-specific IPSec negotiation prevents the EdgeConnect overlay path from forming.","Keep the BIO on a verified healthy tunnel and preserve negotiation evidence before any approved correction.","Correct the peer-aligned IPSec parameters and continuously test primary and backup tunnel establishment."),
 ("PATH_BROWNOUT","HPE Aruba Networking EdgeConnect","show interfaces tunnel <tunnel-name> stats latency","show interfaces tunnel <tunnel-name> stats ipsec","Path characterization shows rising loss, latency, and jitter on one circuit while the alternate circuit remains within the overlay SLA.","An underlay brownout degrades the selected EdgeConnect tunnel without taking it fully down.","Allow the reviewed bonding policy to exclude the brownout path or steer to the healthy circuit.","Repair the provider path and retain SLA thresholds, circuit diversity, and brownout alerts."),
 ("BIO_CLASSIFICATION","HPE Aruba Networking EdgeConnect Orchestrator","Orchestrator > Configuration > Overlays & Security > Business Intent Overlays","Orchestrator > Monitoring > Flows","The application is identified correctly but matches an earlier BIO whose overlay ACL has broader criteria than the intended overlay.","Top-down BIO matching places the application in the wrong Business Intent Overlay.","Move or narrow the conflicting match through an approved overlay policy change.","Add representative application classification tests and peer review for BIO ordering and ACL scope."),
 ("BIO_PATH_POLICY","HPE Aruba Networking EdgeConnect Orchestrator","Orchestrator BIO primary/backup interface and bonding-policy review","Orchestrator circuit performance review","The intended circuit is not primary for the matched BIO even though its performance is healthy.","The applied BIO link-bonding policy does not express the intended application path preference.","Use the documented healthy path through a reviewed BIO policy correction.","Version overlay intent and validate applied overlays, interface labels, bonding policy, and failover behavior."),
 ("ZSCALER_ORCHESTRATION","HPE Aruba Networking EdgeConnect with Zscaler","Orchestrator > Configuration > Cloud Services > Service Orchestration","show interfaces tunnel summary","The Zscaler IPSec tunnel exists but its IKE identity does not match the remote endpoint record and the orchestrated IP SLA is unhealthy.","A service-orchestration identity mismatch prevents the Zscaler tunnel from becoming usable.","Keep breakout on a verified alternate service tunnel and pause automated retries only through approval.","Align generated IKE IDs with Zscaler endpoints and monitor orchestrated tunnel plus IP SLA state."),
 ("ZSCALER_BREAKOUT","HPE Aruba Networking EdgeConnect with Zscaler","Orchestrator > Business Intent Overlays > Breakout Traffic to Internet & Cloud Services","Orchestrator > Monitoring > Flows","Zscaler association is healthy, but the application's matched BIO does not include Zscaler Cloud in its preferred breakout policy order.","The BIO breakout policy omits Zscaler for the affected application class.","Use the approved existing breakout path while the BIO policy is reviewed.","Test application classification and preferred cloud-service policy order before applying overlays."),
 ("ROUTE_SELECTION","HPE Aruba Networking EdgeConnect Orchestrator","Orchestrator > Configuration > Routes > Find Preferred Route","show interfaces tunnel peers","The prefix is present through two peers; equal protocol values are broken by an unintended lower EdgeConnect Peer Priority.","An incorrect Peer Priority makes the appliance select the unintended SD-WAN fabric route.","Use the verified alternate route only after a reviewed priority or route-map correction.","Manage Peer Priority and route maps as intent and test preferred routes per segment before deployment."),
 ("APPLIANCE_DISCOVERY","HPE Aruba Networking EdgeConnect Orchestrator","EdgeConnect local UI/CLI management and WAN reachability check","Orchestrator > Appliances Discovered","The virtual appliance management vNIC is mapped to the wrong port group and cannot reach Orchestrator although its serial and account data are valid.","Incorrect EC-V management vNIC placement prevents appliance discovery and orchestration.","Correct the approved virtual port-group mapping and validate management reachability.","Template vNIC ordering and test Cloud Portal and Orchestrator reachability during provisioning."),
]}

def build(specialty):
 sites=["Mumbai","London","Chicago","Singapore"]
 for family,platform,c1,c2,evidence,cause,temp,permanent in CURRICULA[specialty]:
  for n,site in enumerate(sites,1):
   iid=f"SIM-{specialty.upper()}-{family}-{n:02d}"
   answer={"issueSummary":f"{site} {specialty} service degradation requires evidence-led diagnosis.","evidence":[evidence],"validationChecks":[c1,c2],"rootCause":cause,"temporaryFix":temp,"permanentFix":permanent,"verification":"Repeat the affected transaction, confirm control-plane and data-plane recovery, and compare fresh counters with the baseline.","rollback":"Restore the versioned prior configuration if validation fails.","escalation":"Require human approval for configuration or policy changes and vendor escalation if read-only evidence remains inconclusive.","confidence":0.92,"dataOrigin":"SIMULATION"}
   yield {"trainingReady":True,"messages":[{"role":"system","content":f"You are a senior {specialty} engineer. Use supplied evidence only, issue-specific read-only commands, rollback, verification and escalation. Return compact JSON and label simulation."},{"role":"user","content":f"Investigate the {family.lower().replace('_',' ')} incident on {platform} at {site}; provide root cause, temporary fix and permanent fix."},{"role":"assistant","content":json.dumps(answer,separators=(',',':'))}],"provenance":{"domain":"NETWORK","specialty":specialty.upper(),"incidentId":iid,"incidentFamily":specialty+":"+family,"mode":"SIMULATION","source":"CURATED_SYNTHETIC_DEMO","curationType":"USER_AUTHORIZED_SYNTHETIC","reviewerId":"DEMO-CURRICULUM-AUTHORIZATION","reviewEventId":"CURATE-"+iid},"reviewNotice":"Synthetic demo supervision; not production evidence or a human incident review."}

def main():
 p=argparse.ArgumentParser();p.add_argument('--specialty',choices=CURRICULA,required=True);p.add_argument('--output',type=Path,required=True);a=p.parse_args();rows=list(build(a.specialty));a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(''.join(json.dumps(r,ensure_ascii=False)+'\n' for r in rows),encoding='utf-8');print(json.dumps({'specialty':a.specialty,'created':len(rows),'families':len(CURRICULA[a.specialty])}))
if __name__=='__main__':main()
