"""Construct an independent evidence-first Middleware V4 curriculum.

This does not edit V3, benchmark cases, or adapters.  Records are newly
written with explicit evidence progression and the canonical V4 response.
"""
import json, hashlib, re
from collections import Counter
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]; OUT=ROOT/'.data/training/prepared-domain-v4-reconstructed/middleware'; CONTRACT=ROOT/'training/contracts/structured-contract-v4.json'
SPECS=[
 ('JVM_RUNTIME','JVM allocation pressure','heap occupancy, promotion rate, and GC pause telemetry','JVM metrics and GC logs','Database',['DATABASE']),
 ('THREAD_POOL','application thread-pool saturation','thread dump shows blocked workers and queue depth','thread dump and request metrics','CloudOps',['CLOUDOPS']),
 ('CONNECTION_POOL','database connection-pool exhaustion','active connections equal pool limit while database accepts probes','pool metrics and database session telemetry','Database',['DATABASE']),
 ('RABBITMQ_QUEUE','RabbitMQ unacknowledged backlog','one consumer has rising unacknowledged messages while broker health is normal','queue and consumer metrics','Database',['DATABASE']),
 ('KAFKA_LAG','Kafka consumer partition skew','one partition lags while producer rate and other partitions remain normal','consumer-group and partition metrics','DevOps',['DEVOPS']),
 ('WEBLOGIC_STUCK','WebLogic stuck execution threads','repeated thread dumps show the same request frames and queue growth','thread dumps and request latency','Network',['NETWORK']),
 ('WEBSPHERE_TLS','WebSphere certificate alias mismatch','handshake traces show alias mismatch and trust-chain metadata is consistent','TLS handshake and certificate inventory','Cyber',['CYBER']),
 ('DOWNSTREAM_TIMEOUT','downstream service timeout budget','correlated request IDs show downstream latency consumes the gateway budget','distributed traces and dependency health','CloudOps',['CLOUDOPS']),
 ('RETRY_AMPLIFICATION','gateway retry amplification','retry counters rise while upstream returns transient failures and backend capacity is normal','gateway logs and retry metrics','DevOps',['DEVOPS']),
 ('GC_PROMOTION','JVM promotion-pressure pauses','GC logs show repeated promotion pauses with allocation-rate increase','GC logs and heap metrics','Linux',['LINUX']),
 ('TOMCAT_EXECUTOR','Tomcat executor queue saturation','executor queue and active-thread metrics reach configured limits','JMX executor metrics and access logs','CloudOps',['CLOUDOPS']),
 ('TLS_TRUSTSTORE','middleware trust-store mismatch','client handshake identifies a missing issuing certificate while service certificate is current','handshake trace and trust-store inventory','Cyber',['CYBER'])]
STATES=['INSUFFICIENT_EVIDENCE','SUSPECTED','SUPPORTED','CONFIRMED','ELIMINATED']
def record(spec,state,index,split):
 family,mechanism,evidence,tool,owner,deps=spec; deps=deps if index%3==0 else []; site=['north','south','core','edge','lab'][index%5]; case=f'MWV4-{family}-{index:03d}'; event=f'event-{family.lower()}-{index:03d}'; context=['morning batch window with steady request volume','post-deployment interval with unchanged dependency versions','peak-hour traffic with a healthy comparator slice','certificate rotation rehearsal in an isolated lane','consumer rebalance window with stable broker health','blue-green validation interval before any cutover','regional failover drill with no approved mutation','nightly workload under normal database latency','canary observation with unchanged application binary','capacity review window with baseline metrics'][index%10]
 initial=f'{site} middleware telemetry event {event} during {context} reports a user-visible symptom associated with {mechanism}; no state-changing action has been executed.'
 if state=='INSUFFICIENT_EVIDENCE': facts=['INITIAL_SIGNAL']; extra=['No mechanism-specific diagnostic evidence is available yet.']; missing=[evidence, f'known-good comparator for {mechanism}']; hyp='A middleware mechanism may be involved'; hstate='INSUFFICIENT_EVIDENCE'; he=[]; action=f'Collect {evidence} and a known-good comparator'; rem='Collect read-only diagnostics only; no remediation is eligible.'; abst=True
 elif state=='SUSPECTED': facts=['INITIAL_SIGNAL',f'An initial {mechanism} indicator is plausible but not independently discriminating.']; extra=[]; missing=[evidence]; hyp=mechanism; hstate='SUSPECTED'; he=[facts[1]]; action=f'Collect {evidence} to test the {mechanism} hypothesis'; rem='Continue read-only diagnostics; no configuration-changing remediation is eligible.'; abst=False
 elif state=='SUPPORTED': facts=['INITIAL_SIGNAL',f'{evidence} is observed from one diagnostic source while the strongest dependency comparator remains healthy.']; extra=[]; missing=[f'confirmation evidence for {mechanism}']; hyp=mechanism; hstate='SUPPORTED'; he=[facts[1]]; action=f'Collect confirmation evidence for {mechanism}'; rem='A potential remediation may be documented as NOT_ELIGIBLE_FOR_EXECUTION_PENDING_CONFIRMATION_AND_APPROVAL.'; abst=False
 elif state=='CONFIRMED': facts=['INITIAL_SIGNAL',f'{evidence} is present.',f'Independent corroboration from {tool} and a healthy comparator establishes the mechanism.']; extra=[]; missing=[]; hyp=mechanism; hstate='CONFIRMED'; he=facts[1:]; action=f'Verify blast radius and approval prerequisites for {mechanism} remediation'; rem=f'Propose a controlled {mechanism} remediation subject to HITL approval, risk review, rollback, execution, and verification.'; abst=False
 else: facts=['INITIAL_SIGNAL',f'Contradictory evidence shows the {mechanism} indicators are absent while the symptom persists elsewhere.']; extra=[]; missing=[f'owner evidence for the alternative mechanism']; hyp=mechanism; hstate='ELIMINATED'; he=[facts[1]]; action=f'Collect evidence for the alternative dependency rather than remediating {mechanism}'; rem='Do not remediate the eliminated hypothesis; continue read-only investigation.'; abst=False
 a={'domain':'MIDDLEWARE','technology':mechanism,'vendor':'Generic','assessment':initial,'observedFacts':facts+extra,'hypotheses':[{'cause':hyp,'status':hstate,'evidence':he}],'missingEvidence':missing,'nextDiagnosticAction':{'action':action,'reason':'The next step must discriminate the hypothesis using supplied evidence.'},'toolSelection':{'tool':tool,'reason':f'{tool} is the least-invasive evidence source for {mechanism}.'},'rootCause':{'state':hstate,'cause':mechanism if state in ('SUPPORTED','CONFIRMED') else '','evidence':he if state=='CONFIRMED' else []},'remediation':rem,'risk':'No mutation is authorized without the state-appropriate approval controls.','rollback':'If an approved change is executed, restore the last known-good configuration and verify service health.','verification':f'Repeat the focused {mechanism} validation and compare the same affected scope with the healthy comparator.','abstain':abst,'abstentionReason':'Available evidence cannot discriminate the viable hypotheses.' if abst else '','escalateTo':deps}
 prompt=f'Investigate a Middleware {mechanism} event at service slice {site}. Evidence supplied in this record is authoritative. Separate observed facts, hypotheses, evidence state, safe diagnostics, remediation eligibility, rollback, verification, and escalation. Return exactly one bare JSON object matching structured-contract-v4; no Markdown or surrounding text.'
 return {'messages':[{'role':'system','content':'You are the CloudZero Middleware Twin. Use structured-contract-v4 exactly. Return one bare JSON object only; never use Markdown fences. Evidence determines state and state determines allowed action.'},{'role':'user','content':prompt+' '+initial+' Evidence: '+' '.join(facts+extra)},{'role':'assistant','content':json.dumps(a,separators=(',',':'))}], 'provenance':{'domain':'MIDDLEWARE','incidentId':case,'incidentFamily':f'MWV4:{family}','mode':'SIMULATION','source':'MIDDLEWARE_V4_RECONSTRUCTED','split':split},'metadata':{'contractVersion':'structured-contract-v4','evidenceState':state,'crossDomain':bool(deps),'crossTwinDependencies':deps,'curriculumIndex':index},'trainingReady':False}
def main():
 rows=[]
 for fi,spec in enumerate(SPECS):
  split='validation' if fi in {2,6,10} else 'train'
  for i in range(10): rows.append(record(spec,STATES[i%5],fi*10+i,split))
 OUT.mkdir(parents=True,exist_ok=True); train=[r for r in rows if r['provenance']['split']=='train']; val=[r for r in rows if r['provenance']['split']=='validation']
 (OUT/'train.jsonl').write_text('\n'.join(json.dumps(r,separators=(',',':')) for r in train)+'\n'); (OUT/'validation.jsonl').write_text('\n'.join(json.dumps(r,separators=(',',':')) for r in val)+'\n')
 print(json.dumps({'total':len(rows),'train':len(train),'validation':len(val),'states':dict(Counter(r['metadata']['evidenceState'] for r in rows))},indent=2))
if __name__=='__main__':main()
