import React, { useMemo, useState } from "react";
import type { CrossSiloWorkflow, DigitalTwinAgent, HITLApproval, IncidentEvidence, ServiceNowIncident, SystemLog, WorkflowInstance } from "../types";
import { useInvestigationViewModel } from "../hooks/useInvestigationViewModel";

interface Props { incident?: ServiceNowIncident; incidents: ServiceNowIncident[]; agents: DigitalTwinAgent[]; workflows: WorkflowInstance[]; approvals: HITLApproval[]; systemLogs: SystemLog[]; crossSiloWorkflows: CrossSiloWorkflow[]; evidence?: IncidentEvidence[]; rawEvents?: Array<Record<string, unknown>>; onSelectIncident: (id: string) => void; onBack: () => void; onTakeover: (id: string) => Promise<void>; }
const stateTone: Record<string, string> = { AVAILABLE: "border-slate-200 bg-slate-50 text-slate-600", STARTING: "border-blue-200 bg-blue-50 text-blue-700", WAITING_FOR_TOOL: "border-amber-200 bg-amber-50 text-amber-800", WAITING_FOR_TWIN: "border-amber-200 bg-amber-50 text-amber-800", EVIDENCE_RECEIVED: "border-cyan-200 bg-cyan-50 text-cyan-800", COMPLETED: "border-emerald-200 bg-emerald-50 text-emerald-700", FAILED: "border-rose-200 bg-rose-50 text-rose-700", TIMED_OUT: "border-rose-200 bg-rose-50 text-rose-700", NOT_REQUIRED: "border-slate-200 bg-slate-50 text-slate-400" };
const hypothesisTone: Record<string, string> = { INSUFFICIENT_EVIDENCE: "bg-slate-100 text-slate-600", SUSPECTED: "bg-amber-100 text-amber-800", SUPPORTED: "bg-blue-100 text-blue-800", CONFIRMED: "bg-emerald-100 text-emerald-800", ELIMINATED: "bg-rose-50 text-rose-700", UNKNOWN: "bg-slate-100 text-slate-500" };

function readableEvidence(summary: string) {
  if (!summary.includes("{")) return summary;
  const finding = summary.match(/"finding"\s*:\s*"((?:\\.|[^"\\])*)"/i)?.[1];
  return finding?.replace(/\\"/g, '"').replace(/\\n/g, " ") || summary.split("{")[0].replace(/[:\s]+$/, "") || "Recorded diagnostic evidence is available in Developer Details.";
}

export default function InvestigationView(props: Props) {
  const [developerDetails, setDeveloperDetails] = useState(false);
  const [busy, setBusy] = useState(false);
  const model = useInvestigationViewModel(props);
  const incident = model.incident;
  const timeline = useMemo(() => developerDetails ? model.timeline : model.timeline.filter(item => item.kind !== "SYSTEM").slice(-14), [developerDetails, model.timeline]);
  if (!incident) return <section className="min-h-full bg-slate-100 p-6 dark:bg-slate-950"><div className="mx-auto max-w-5xl rounded-xl border border-slate-200 bg-white p-10 text-center dark:border-slate-800 dark:bg-slate-900"><h1 className="text-xl font-bold">No incident selected</h1><p className="mt-2 text-sm text-slate-500">Choose an incident to open its investigation.</p><button onClick={props.onBack} className="mt-5 rounded-md bg-blue-600 px-4 py-2 text-sm font-semibold text-white">Back to incidents</button></div></section>;
  return <section className="min-h-full bg-slate-100 p-4 text-slate-900 sm:p-6 dark:bg-slate-950 dark:text-slate-100">
    <div className="mx-auto max-w-[1600px]">
      <header className="mb-4 flex flex-wrap items-end justify-between gap-3"><div className="min-w-0"><button onClick={props.onBack} className="mb-2 text-xs font-semibold text-blue-700 dark:text-blue-300">← All incidents</button><div className="flex flex-wrap items-center gap-2"><span className="max-w-full truncate font-mono text-xs text-slate-500">{incident.id}</span><span className="rounded border border-rose-200 bg-rose-50 px-2 py-1 text-[10px] font-bold text-rose-700">{incident.severity}</span><span className="rounded border border-blue-200 bg-blue-50 px-2 py-1 text-[10px] font-bold text-blue-700">{model.lifecycle.displayState}</span></div><h1 className="mt-2 text-xl font-bold tracking-tight">{incident.shortDescription}</h1><p className="mt-1 text-xs text-slate-500">{incident.cmdbName} · Owner {incident.assignedTo} · {incident.elapsedMinutes} minutes elapsed</p></div><div className="flex max-w-full items-center gap-2"><select value={incident.id} onChange={event => props.onSelectIncident(event.target.value)} className="max-w-[min(70vw,620px)] rounded-md border border-slate-300 bg-white px-3 py-2 text-xs dark:border-slate-700 dark:bg-slate-900">{props.incidents.map(item => <option key={item.id} value={item.id}>{item.id} · {item.shortDescription}</option>)}</select>{!incident.assignedTo.includes("Twin") && <button disabled={busy} onClick={async () => { setBusy(true); try { await props.onTakeover(incident.id); } finally { setBusy(false); } }} className="rounded-md bg-blue-600 px-3 py-2 text-xs font-semibold text-white disabled:opacity-50">{busy ? "Engaging…" : "Engage Twins"}</button>}</div></header>
      <div className="cz-investigation-layout grid gap-4 xl:grid-cols-[220px_minmax(0,1fr)_340px]">
        <section className="rounded-xl border border-slate-200 bg-white p-4 shadow-sm dark:border-slate-800 dark:bg-slate-900"><h2 className="text-xs font-bold uppercase tracking-wider text-slate-500">Digital Twins</h2><div className="mt-3 space-y-2">{model.twins.map(twin => <article key={twin.id} className={`rounded-lg border p-3 ${twin.participating ? "border-blue-200" : "border-slate-200 dark:border-slate-800"}`}><div className="flex items-center justify-between gap-2"><h3 className="text-xs font-bold">{twin.name}</h3><span className={`rounded px-1.5 py-1 text-[9px] font-bold ${stateTone[twin.state]}`}>{twin.state.replaceAll("_", " ")}</span></div>{twin.currentTask && <p className="mt-1 line-clamp-3 text-[10px] leading-4 text-slate-500 dark:text-slate-400">{readableEvidence(twin.currentTask)}</p>}</article>)}</div></section>
        <section className="min-w-0 rounded-xl border border-slate-200 bg-white p-4 shadow-sm dark:border-slate-800 dark:bg-slate-900"><div className="flex items-center justify-between gap-3"><div><h2 className="text-xs font-bold uppercase tracking-wider text-slate-500">Orchestrator Investigation</h2><p className="mt-1 text-xs text-slate-500">Detect → investigate → correlate → diagnose → act → verify.</p></div><span className="rounded bg-slate-100 px-2 py-1 text-[10px] font-semibold text-slate-600 dark:bg-slate-800 dark:text-slate-300">{timeline.length} {developerDetails ? "records" : "milestones"}</span></div><ol className="mt-4 max-h-[calc(100vh-250px)] space-y-3 overflow-y-auto pr-1" aria-live="polite">{timeline.length ? timeline.map(event => <li key={event.id} className="rounded-lg border border-slate-200 p-3 dark:border-slate-800"><div className="flex items-start justify-between gap-3"><div><p className="text-[9px] font-bold uppercase tracking-wider text-blue-700 dark:text-blue-300">{event.kind === "A2A" ? "CloudZero collaboration" : event.kind === "EVIDENCE" ? "Diagnostic evidence" : event.kind.replaceAll("_", " ")}</p><h3 className="mt-1 text-sm font-semibold">{event.title}</h3></div>{event.at && <time className="shrink-0 text-[10px] text-slate-500 dark:text-slate-400">{new Date(event.at).toLocaleTimeString()}</time>}</div><p className="mt-2 break-words text-xs leading-5 text-slate-600 dark:text-slate-300">{readableEvidence(event.detail)}</p>{developerDetails && <details className="mt-2"><summary className="cursor-pointer text-[10px] font-semibold text-blue-700 dark:text-blue-300">Developer Details</summary><pre className="mt-2 max-h-40 overflow-auto rounded bg-slate-950 p-2 text-[10px] text-emerald-300">{JSON.stringify(event.raw, null, 2)}</pre></details>}</li>) : <li className="rounded-lg border border-dashed border-slate-300 p-6 text-center text-xs text-slate-500">Waiting for investigation evidence…</li>}</ol><label className="mt-4 flex items-center gap-2 text-xs text-slate-500 dark:text-slate-400"><input type="checkbox" checked={developerDetails} onChange={event => setDeveloperDetails(event.target.checked)} /> Developer Details <span>({model.timeline.length} audit records)</span></label></section>
        <aside className="space-y-4"><section className="rounded-xl border border-slate-200 bg-white p-4 shadow-sm dark:border-slate-800 dark:bg-slate-900"><div className="flex items-center justify-between"><h2 className="text-xs font-bold uppercase tracking-wider text-slate-500">Evidence</h2><span className="text-xs font-bold">{model.evidence.length}</span></div>{model.evidence.length ? <div className="mt-3 space-y-2">{model.evidence.slice(0, 5).map(item => <article key={item.id} className="min-w-0 rounded-lg border border-slate-200 p-3 dark:border-slate-800"><p className="text-[10px] font-semibold text-blue-700 dark:text-blue-300">{item.source}</p><p className="mt-1 break-words text-xs leading-5">{readableEvidence(item.summary || "Recorded diagnostic evidence.")}</p>{developerDetails && <details className="mt-2"><summary className="cursor-pointer text-[10px] text-slate-500">Developer Details</summary><pre className="mt-2 max-h-40 overflow-auto rounded bg-slate-950 p-2 text-[10px] text-emerald-300">{JSON.stringify(item, null, 2)}</pre></details>}</article>)}</div> : <p className="mt-3 text-xs text-slate-500">Waiting for evidence…</p>}</section>
          <section className="rounded-xl border border-slate-200 bg-white p-4 shadow-sm dark:border-slate-800 dark:bg-slate-900"><h2 className="text-xs font-bold uppercase tracking-wider text-slate-500">Hypotheses</h2>{model.hypotheses.length ? <div className="mt-3 space-y-2">{model.hypotheses.map(item => <article key={item.id} className="rounded-lg border border-slate-200 p-3 dark:border-slate-800"><div className="flex items-start justify-between gap-2"><p className="text-xs font-semibold">{item.title}</p><span className={`shrink-0 rounded px-1.5 py-1 text-[9px] font-bold ${hypothesisTone[item.state]}`}>{item.state.replaceAll("_", " ")}</span></div><p className="mt-1 text-[10px] text-slate-500 dark:text-slate-400">{item.detail}</p></article>)}</div> : <p className="mt-3 text-xs text-slate-500">No RCA established.</p>}</section>
          <section className="rounded-xl border border-slate-200 bg-white p-4 shadow-sm dark:border-slate-800 dark:bg-slate-900"><h2 className="text-xs font-bold uppercase tracking-wider text-slate-500">Root Cause Analysis</h2><p className="mt-3 text-sm font-semibold">{model.rca.title || "No RCA established"}</p><div className="mt-2 flex flex-wrap gap-2"><span className={`rounded px-2 py-1 text-[10px] font-bold ${hypothesisTone[model.rca.state]}`}>Hypothesis: {model.rca.state.replaceAll("_", " ")}</span><span className={`rounded px-2 py-1 text-[10px] font-bold ${hypothesisTone[model.rca.validatedState]}`}>Guardrail: {model.rca.validatedState.replaceAll("_", " ")}</span></div><p className="mt-2 text-[10px] text-slate-500 dark:text-slate-400">{model.rca.evidenceCount} incident-bound evidence records</p><p className="mt-3 text-xs">Remediation: {model.remediation.proposed || "No remediation proposed"}</p><p className="mt-1 text-xs text-slate-500 dark:text-slate-400">Approval: {model.approval ? model.approval.status : "Approval not required yet"} · Verification: {model.verification.state}</p></section></aside>
      </div>
    </div>
  </section>;
}
