import { useEffect, useMemo, useRef, useState, type FormEvent } from "react";
import { ArrowRight, BookOpenCheck, FileCheck2, FileText, Loader2, LockKeyhole, SearchCheck, ShieldCheck, UploadCloud } from "lucide-react";
import type { ServiceNowIncident, SSOUser } from "../types";
import { UserRole } from "../types";
import SopVerificationPanel from "./SopVerificationPanel";

interface KnowledgeDocument { documentId: string; title: string; sourceDocumentHash: string; pageCount: number; chunkCount: number }
interface KnowledgeStatus { sourceBoundary: string; documents: KnowledgeDocument[]; chunkCount: number }

export default function SopKnowledgeView({ currentUser, incidents }: { currentUser: SSOUser; incidents: ServiceNowIncident[] }) {
  const [status, setStatus] = useState<KnowledgeStatus | null>(null);
  const [statusError, setStatusError] = useState<string | null>(null);
  const [loading, setLoading] = useState(true);
  const [uploading, setUploading] = useState(false);
  const [uploadMessage, setUploadMessage] = useState<{ tone: "success" | "error"; text: string } | null>(null);
  const [title, setTitle] = useState("");
  const [file, setFile] = useState<File | null>(null);
  const [incidentId, setIncidentId] = useState("");
  const fileRef = useRef<HTMLInputElement>(null);
  const mayUpload = [UserRole.ADMIN, UserRole.DEVOPS, UserRole.NRE].includes(currentUser.role as UserRole);
  const orderedIncidents = useMemo(() => [...incidents].sort((a, b) => a.severity.localeCompare(b.severity) || b.openedAt.localeCompare(a.openedAt)), [incidents]);

  const loadStatus = async () => {
    setLoading(true); setStatusError(null);
    try { const response = await fetch("/api/knowledge/status", { headers: { Accept: "application/json" }, cache: "no-store" }); const data = await response.json(); if (!response.ok) throw new Error(data.error || `HTTP ${response.status}`); setStatus(data); }
    catch (failure) { setStatusError(failure instanceof Error ? failure.message : "SOP library unavailable."); }
    finally { setLoading(false); }
  };
  useEffect(() => { loadStatus(); }, []);
  useEffect(() => { if (!incidentId && orderedIncidents.length) setIncidentId(orderedIncidents[0].id); }, [incidentId, orderedIncidents]);

  const upload = async (event: FormEvent) => {
    event.preventDefault(); setUploadMessage(null);
    if (!file) return setUploadMessage({ tone: "error", text: "Choose a Markdown or text SOP first." });
    if (file.size > 2 * 1024 * 1024) return setUploadMessage({ tone: "error", text: "SOP files must be 2 MB or smaller." });
    if (!/\.(md|txt)$/i.test(file.name)) return setUploadMessage({ tone: "error", text: "Only .md and .txt files are accepted." });
    setUploading(true);
    try {
      const response = await fetch("/api/knowledge/documents", { method: "POST", headers: { "Content-Type": "application/json", Accept: "application/json" }, body: JSON.stringify({ title: title.trim() || file.name.replace(/\.[^.]+$/, ""), fileName: file.name, content: await file.text() }) });
      const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.error || `Upload returned HTTP ${response.status}.`);
      setUploadMessage({ tone: "success", text: data.status === "already_indexed" ? "This approved SOP is already indexed." : "SOP indexed and ready for grounded retrieval." }); setTitle(""); setFile(null); if (fileRef.current) fileRef.current.value = ""; await loadStatus();
    } catch (failure) { setUploadMessage({ tone: "error", text: failure instanceof Error ? failure.message : "SOP upload failed." }); }
    finally { setUploading(false); }
  };

  const steps = [{ icon: UploadCloud, label: "Attach SOP" }, { icon: SearchCheck, label: "Retrieve evidence" }, { icon: BookOpenCheck, label: "Prioritize checks" }, { icon: FileCheck2, label: "Operator verifies" }, { icon: ShieldCheck, label: "Diagnose" }];
  return <section className="min-h-full bg-slate-100 p-4 text-slate-900 sm:p-6 dark:bg-slate-950 dark:text-slate-100"><div className="mx-auto max-w-[1500px] space-y-5">
    <header className="flex flex-wrap items-start justify-between gap-4"><div><p className="font-mono text-[10px] font-bold uppercase tracking-[0.2em] text-blue-700 dark:text-blue-300">Grounded operations</p><h1 className="mt-2 text-2xl font-bold tracking-tight">SOP Library & Verification</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-600 dark:text-slate-300">Attach approved operating procedures and retrieve citation-bound checks for critical incidents. Document content is treated as data—not trusted instructions.</p></div><span className="flex items-center gap-2 rounded-lg border border-teal-200 bg-teal-50 px-3 py-2 text-xs font-bold text-teal-800 dark:border-teal-900 dark:bg-teal-950/40 dark:text-teal-200"><LockKeyhole className="h-4 w-4" />Read-only · No execution</span></header>
    <div className="overflow-x-auto rounded-xl border border-slate-200 bg-white px-4 py-3 shadow-sm dark:border-slate-800 dark:bg-slate-900"><ol className="flex min-w-[720px] items-center justify-between">{steps.map((step, index) => <li key={step.label} className="flex flex-1 items-center"><div className="flex items-center gap-2"><span className="grid h-8 w-8 place-items-center rounded-lg bg-blue-50 text-blue-700 dark:bg-blue-950 dark:text-blue-300"><step.icon className="h-4 w-4" /></span><span className="text-xs font-semibold">{step.label}</span></div>{index < steps.length - 1 && <ArrowRight className="mx-3 h-4 w-4 flex-1 text-slate-300 dark:text-slate-700" />}</li>)}</ol></div>
    <div className="grid gap-3 sm:grid-cols-3"><article className="rounded-xl border border-slate-200 bg-white p-4 shadow-sm dark:border-slate-800 dark:bg-slate-900"><p className="text-[10px] font-bold uppercase tracking-wider text-slate-500">Approved documents</p><p className="mt-2 text-2xl font-bold">{loading ? "—" : status?.documents.length || 0}</p></article><article className="rounded-xl border border-slate-200 bg-white p-4 shadow-sm dark:border-slate-800 dark:bg-slate-900"><p className="text-[10px] font-bold uppercase tracking-wider text-slate-500">Indexed chunks</p><p className="mt-2 text-2xl font-bold">{loading ? "—" : status?.chunkCount || 0}</p></article><article className="rounded-xl border border-teal-200 bg-teal-50 p-4 dark:border-teal-900 dark:bg-teal-950/30"><p className="text-[10px] font-bold uppercase tracking-wider text-teal-700 dark:text-teal-300">Grounding boundary</p><p className="mt-2 text-sm font-bold">Approved local SOPs only</p></article></div>
    {statusError && <p role="alert" className="rounded-lg border border-rose-200 bg-rose-50 p-3 text-xs text-rose-700 dark:border-rose-900 dark:bg-rose-950/30 dark:text-rose-300">Library status unavailable: {statusError}</p>}
    <div className="grid gap-5 xl:grid-cols-[minmax(0,0.85fr)_minmax(0,1.15fr)]"><div className="space-y-5"><section className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900"><div className="flex items-center gap-3"><UploadCloud className="h-5 w-5 text-blue-600 dark:text-blue-300" /><div><h2 className="text-sm font-bold">Attach approved SOP</h2><p className="text-xs text-slate-500">Markdown or plain text · maximum 2 MB</p></div></div>{mayUpload ? <form onSubmit={upload} className="mt-4 space-y-3"><label className="block text-xs font-semibold">Document title<input value={title} onChange={event => setTitle(event.target.value)} placeholder="Optional — inferred from filename" className="mt-1.5 min-h-11 w-full rounded-md border border-slate-300 bg-white px-3 text-sm outline-none focus:ring-2 focus:ring-blue-500 dark:border-slate-700 dark:bg-slate-950" /></label><label className="flex cursor-pointer items-center gap-3 rounded-lg border border-dashed border-slate-300 p-4 hover:border-blue-400 dark:border-slate-700"><FileText className="h-5 w-5 text-slate-400" /><span className="min-w-0 flex-1 truncate text-xs">{file?.name || "Choose .md or .txt SOP"}</span><input ref={fileRef} type="file" accept=".md,.txt,text/markdown,text/plain" onChange={event => setFile(event.target.files?.[0] || null)} className="sr-only" /></label><button disabled={uploading || !file} className="flex min-h-11 w-full items-center justify-center gap-2 rounded-md bg-slate-900 px-4 text-sm font-semibold text-white disabled:opacity-50 dark:bg-blue-600">{uploading && <Loader2 className="h-4 w-4 animate-spin" />}{uploading ? "Indexing SOP…" : "Attach and index"}</button>{uploadMessage && <p role="status" className={`rounded-md p-3 text-xs ${uploadMessage.tone === "success" ? "bg-teal-50 text-teal-800 dark:bg-teal-950/30 dark:text-teal-200" : "bg-rose-50 text-rose-700 dark:bg-rose-950/30 dark:text-rose-300"}`}>{uploadMessage.text}</p>}</form> : <div className="mt-4 rounded-lg border border-slate-200 bg-slate-50 p-4 text-xs leading-5 text-slate-600 dark:border-slate-800 dark:bg-slate-950/50 dark:text-slate-300">Your role has read-only access. Administrators, DevOps Platform Engineers, and NREs can attach approved SOPs.</div>}</section>
      <section className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900"><h2 className="text-sm font-bold">Indexed provenance</h2><div className="mt-3 space-y-2">{loading ? <p className="text-xs text-slate-500">Loading indexed documents…</p> : status?.documents.length ? status.documents.map(document => <article key={document.documentId} className="rounded-lg border border-slate-200 p-3 dark:border-slate-800"><div className="flex items-start gap-3"><FileText className="mt-0.5 h-4 w-4 shrink-0 text-blue-600 dark:text-blue-300" /><div className="min-w-0"><h3 className="truncate text-xs font-semibold">{document.title}</h3><p className="mt-1 font-mono text-[9px] text-slate-500">{document.documentId.slice(0, 16)}… · {document.pageCount} pages · {document.chunkCount} chunks</p><p className="mt-1 truncate font-mono text-[9px] text-slate-400">SHA-256 {document.sourceDocumentHash.slice(0, 20)}…</p></div></div></article>) : <p className="rounded-lg border border-dashed border-slate-300 p-5 text-center text-xs text-slate-500 dark:border-slate-700">No approved SOPs are indexed yet.</p>}</div></section></div>
      <section className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="font-mono text-[9px] font-bold uppercase tracking-wider text-blue-700 dark:text-blue-300">Incident-bound retrieval</p><h2 className="mt-1 text-lg font-bold">Verification planner</h2><p className="mt-1 text-xs text-slate-500">The model may prioritize approved checks; it cannot execute or authorize them.</p></div><label className="min-w-[260px] flex-1 text-xs font-semibold xl:max-w-md">Critical incident<select value={incidentId} onChange={event => setIncidentId(event.target.value)} className="mt-1.5 min-h-11 w-full rounded-md border border-slate-300 bg-white px-3 text-xs dark:border-slate-700 dark:bg-slate-950"><option value="">Select an incident</option>{orderedIncidents.map(incident => <option key={incident.id} value={incident.id}>{incident.severity.startsWith("P1") || incident.severity.startsWith("P2") ? "● " : ""}{incident.id} · {incident.severity} · {incident.shortDescription}</option>)}</select></label></div><div className="mt-5 border-t border-slate-200 pt-5 dark:border-slate-800">{incidentId ? <SopVerificationPanel incidentId={incidentId} /> : <p className="rounded-lg border border-dashed border-slate-300 p-8 text-center text-sm text-slate-500 dark:border-slate-700">Select an incident to retrieve approved SOP checks.</p>}</div></section></div>
  </div></section>;
}
