import React, { useState } from "react";

export type ExperienceMetrics = { responses: number; respondents: number; ratedTasks: number; coverage: number | null; score: number | null; favorableRate: number | null; helpfulness: number | null; clarity: number | null; trust: number | null; ease: number | null; helpedResolveRate: number | null; firstContactResolutionRate: number | null; attainment: string };
export type IncidentCommitment = { incidentId: string; priority: string; mode: string; policyVersion: string; startedAt: string | null; responseAt: string | null; resolvedAt: string | null; responseTargetSeconds: number | null; resolutionTargetSeconds: number | null; responseSeconds: number | null; resolutionSeconds: number | null; responseStatus: string; resolutionStatus: string; clockBasis: string };
export type ExperiencePolicy = { minimumResponses: number; favorableTarget: number; coverageTarget: number };
const percent = (value: number | null | undefined) => value == null ? "N/A" : `${(value * 100).toFixed(1)}%`;
const formatDuration = (value: number) => {
  const seconds = Math.max(0, Math.round(value));
  const hours = Math.floor(seconds / 3600);
  const minutes = Math.floor((seconds % 3600) / 60);
  const remainder = seconds % 60;
  return [hours ? `${hours}h` : "", minutes ? `${minutes}m` : "", remainder || (!hours && !minutes) ? `${remainder}s` : ""].filter(Boolean).join(" ");
};
const input = "rounded border border-slate-300 dark:border-zinc-700 bg-white dark:bg-zinc-950 px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-indigo-500 disabled:opacity-50";
const emptySurvey = { helpfulness: "", clarity: "", trust: "", ease: "", helpedResolve: "", firstContactResolved: "", comment: "" };

export type JourneyMetrics = { profiles: { id: string; name: string; description: string; targetState: string; thresholds: { interruptionMs: number | null; packetLossPercent: number | null; latencyMs: number | null } }[]; summary: { sessions: number; liveSessions: number; simulatedSessions: number; good: number; poor: number; unknown: number; goodRate: number | null; interruptionP95Ms: number | null; packetLossP95Percent: number | null; authenticationFailures: number; sessionDrops: number; feedbackCount: number }; samples: { id: string; incidentId: string | null; clientId: string; fromAp: string; toAp: string; occurredAt: string; mode: string; source: string; interruptionMs: number | null; packetLossPercent: number | null; latencyMs: number | null; authenticationSucceeded: boolean | null; sessionPreserved: boolean | null; experience: string; evidenceId: string; reason: string }[] };
export function ServiceJourneyXla({ journeys }: { journeys?: JourneyMetrics }) {
  const summary = journeys?.summary;
  const profile = journeys?.profiles.find(item => item.id === "WIRELESS_ROAMING");
  return <section aria-label="Service journey XLA wireless roaming" className="border-l-2 border-indigo-500 bg-slate-50 dark:bg-zinc-900/40 p-4 space-y-4">
    <div className="flex flex-wrap justify-between gap-2"><div><p className="text-xs uppercase tracking-widest text-indigo-700 dark:text-indigo-300">End-to-end user journey</p><h4 className="font-semibold text-lg mt-1">Service journey XLA — Wireless roaming</h4><p className="text-xs text-slate-500 dark:text-zinc-400 mt-1">A client's experience moving from one access point to another: interruption, packet loss, authentication and session continuity.</p></div><span className="text-xs font-mono text-slate-500 dark:text-zinc-400">{profile?.targetState === "CONFIGURED" ? "Journey targets configured" : "Journey targets not configured"}</span></div>
    <div className="grid grid-cols-2 lg:grid-cols-4 gap-4">{[{ label: "Observed journeys", value: summary?.sessions ?? 0, note: `${summary?.liveSessions || 0} live / ${summary?.simulatedSessions || 0} simulated` }, { label: "Good experience", value: percent(summary?.goodRate), note: `${summary?.poor || 0} poor / ${summary?.unknown || 0} unknown` }, { label: "Roaming interruption p95", value: summary?.interruptionP95Ms == null ? "N/A" : `${summary.interruptionP95Ms.toFixed(1)} ms`, note: `Packet loss p95: ${summary?.packetLossP95Percent == null ? "N/A" : `${summary.packetLossP95Percent.toFixed(2)}%`}` }, { label: "Failure signals", value: (summary?.authenticationFailures || 0) + (summary?.sessionDrops || 0), note: `${summary?.authenticationFailures || 0} auth failures / ${summary?.sessionDrops || 0} session drops` }].map(item => <div key={item.label}><p className="text-xs uppercase text-slate-500 dark:text-zinc-400">{item.label}</p><p className="text-2xl font-mono mt-1">{item.value}</p><p className="text-xs text-slate-500 dark:text-zinc-400 mt-1">{item.note}</p></div>)}</div>
    {!journeys?.samples.length ? <p className="border border-dashed border-slate-300 dark:border-zinc-700 p-4 text-sm">Connect per-client roaming telemetry to measure this journey.</p> : <div className="overflow-auto"><table className="w-full min-w-[700px] text-left text-xs"><thead className="text-slate-500 dark:text-zinc-400"><tr>{["Client / incident", "Access point journey", "Measurements", "Experience / evidence"].map(label => <th className="p-2 font-medium" key={label}>{label}</th>)}</tr></thead><tbody className="divide-y divide-slate-200 dark:divide-zinc-800">{journeys.samples.map(sample => <tr key={sample.id}><td className="p-2 align-top"><p className="font-mono">{sample.clientId}</p><p>{sample.incidentId || "No linked incident"}</p><p className="mt-1 text-slate-500 dark:text-zinc-400">{sample.mode} · {new Date(sample.occurredAt).toLocaleString()}</p></td><td className="p-2 align-top font-mono">{sample.fromAp} → {sample.toAp}</td><td className="p-2 align-top"><p>Interruption: {sample.interruptionMs == null ? "Unknown" : `${sample.interruptionMs} ms`}</p><p>Loss: {sample.packetLossPercent == null ? "Unknown" : `${sample.packetLossPercent}%`}</p><p>Latency: {sample.latencyMs == null ? "Unknown" : `${sample.latencyMs} ms`}</p><p>Authentication: {sample.authenticationSucceeded == null ? "Unknown" : sample.authenticationSucceeded ? "Succeeded" : "Failed"}</p><p>Session: {sample.sessionPreserved == null ? "Unknown" : sample.sessionPreserved ? "Preserved" : "Dropped"}</p></td><td className="p-2 align-top max-w-72"><p className={`font-semibold ${sample.experience === "POOR" ? "text-red-700 dark:text-red-300" : ""}`}>{sample.experience}</p><p className="mt-1">{sample.reason}</p><p className="mt-1 font-mono break-all">{sample.evidenceId}</p><p className="text-slate-500 dark:text-zinc-400">{sample.source}</p></td></tr>)}</tbody></table></div>}
    <details className="text-xs text-slate-500 dark:text-zinc-400"><summary className="cursor-pointer font-semibold">Journey measurement methodology</summary><p className="mt-2">XLA follows a unique user journey across the service. Task execution speed and model confidence do not establish a good roaming experience. Without agreed journey thresholds, good experience is N/A; explicit authentication failures and dropped sessions can still establish poor experience. Missing measurements remain unknown.</p><p className="mt-2">Configured thresholds: interruption {profile?.thresholds.interruptionMs ?? "unconfigured"} ms; packet loss {profile?.thresholds.packetLossPercent ?? "unconfigured"}%; latency {profile?.thresholds.latencyMs ?? "unconfigured"} ms. Live and simulation samples are identified separately.</p></details>
  </section>;
}

export function ExperienceScorecard({ metrics, policy }: { metrics?: ExperienceMetrics; policy?: ExperiencePolicy }) {
  return <section aria-label="Interaction feedback" className="border border-slate-200 dark:border-zinc-800 rounded p-4 bg-slate-50 dark:bg-zinc-900/30">
    <div className="flex flex-wrap justify-between gap-2"><div><h4 className="font-semibold">Interaction feedback</h4><p className="text-xs text-slate-500 dark:text-zinc-400 mt-1">How people experienced the twin's help, reported directly by people.</p></div><span className="text-xs font-mono text-indigo-700 dark:text-indigo-300">{metrics?.attainment?.replace("XLA", "FEEDBACK") || "Awaiting feedback"}</span></div>
    <div className="grid grid-cols-2 lg:grid-cols-4 gap-5 mt-4">{[
      { label: "Experience score", value: metrics?.score == null ? "N/A" : `${metrics.score.toFixed(1)} / 100`, note: `${metrics?.responses || 0} responses · ${metrics?.respondents || 0} people` },
      { label: "Favorable experience", value: percent(metrics?.favorableRate), note: `Target ${percent(policy?.favorableTarget ?? .8)}` },
      { label: "Feedback coverage", value: percent(metrics?.coverage), note: `${metrics?.ratedTasks || 0} tasks rated` },
      { label: "Reported resolution", value: percent(metrics?.helpedResolveRate), note: `First contact: ${percent(metrics?.firstContactResolutionRate)}` },
    ].map(item => <div key={item.label}><p className="text-xs uppercase tracking-wide text-slate-500 dark:text-zinc-400">{item.label}</p><p className="text-2xl font-mono mt-2">{item.value}</p><p className="text-xs text-slate-500 dark:text-zinc-400 mt-2">{item.note}</p></div>)}</div>
    <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 border-t border-slate-200 dark:border-zinc-800 mt-4 pt-3">{(["helpfulness", "clarity", "trust", "ease"] as const).map(key => <p key={key} className="text-xs capitalize text-slate-500 dark:text-zinc-400">{key} <strong className="text-slate-800 dark:text-zinc-200 ml-2 font-mono">{metrics?.[key] == null ? "N/A" : `${metrics[key].toFixed(1)} / 5`}</strong></p>)}</div>
    <details className="text-xs mt-4 text-slate-500 dark:text-zinc-400"><summary className="cursor-pointer font-semibold">How interaction feedback is measured</summary><div className="space-y-2 mt-2 leading-relaxed"><p>Experience score normalizes the mean of helpfulness, clarity, trust and ease from 1–5 to 0–100: (mean − 1) × 25. Experience is never inferred from task speed or model confidence.</p><p>Only the latest response per person and task contributes to scores; previous responses remain in history. Coverage is rated completed tasks divided by completed tasks. Resolution rates use explicit yes/no answers; unanswered items are excluded.</p><p>The local feedback target requires at least {policy?.minimumResponses || 10} responses, {percent(policy?.favorableTarget ?? .8)} favorable experience and {percent(policy?.coverageTarget ?? .6)} feedback coverage. No feedback means N/A. This is supplemental feedback, separate from service journey XLA, technical correctness reviews and SLA timing.</p></div></details>
  </section>;
}

export function IncidentSlaTable({ incidents, onSelect }: { incidents: IncidentCommitment[]; onSelect: (id: string) => void }) {
  function timing(seconds: number | null, target: number | null, status: string) {
    return <><span className={`text-xs font-mono ${status === "BREACHED" ? "text-red-700 dark:text-red-300" : status === "MET" ? "text-emerald-700 dark:text-emerald-300" : "text-slate-500 dark:text-zinc-400"}`}>{status}</span><p className="text-xs mt-1">{seconds == null ? "Unknown elapsed" : formatDuration(seconds)} / {target == null ? "Unconfigured target" : `${formatDuration(target)} target`}</p></>;
  }
  return <section aria-label="Incident resolution SLA and observed response"><h4 className="font-semibold">Incident SLA · Resolution & observed response</h4><p className="text-xs text-slate-500 dark:text-zinc-400 mt-1 mb-3">Resolution commitments and observed first response, separate from individual task SLOs. First response has no agreed SLA target. Select an incident to inspect its tasks.</p>
    {!incidents.length ? <p className="p-4 border border-dashed border-slate-300 dark:border-zinc-700 text-sm text-slate-500 dark:text-zinc-400">No incident commitments recorded for these filters.</p> : <div className="overflow-x-auto border-y border-slate-200 dark:border-zinc-800"><table className="w-full text-left min-w-[640px]"><thead className="text-xs uppercase tracking-wide text-slate-500 dark:text-zinc-400 bg-slate-50 dark:bg-zinc-900/40"><tr>{["Incident / mode", "Response", "Resolution", "Clock & policy"].map(label => <th key={label} className="font-medium p-3">{label}</th>)}</tr></thead><tbody className="divide-y divide-slate-200 dark:divide-zinc-800">{incidents.map(incident => <tr key={`${incident.incidentId}:${incident.mode}`}><td className="p-3 align-top"><button className="text-sm text-indigo-700 dark:text-indigo-300 font-mono hover:underline focus:ring-2 focus:ring-indigo-500" onClick={() => onSelect(incident.incidentId)}>{incident.incidentId}</button><p className="text-xs text-slate-500 dark:text-zinc-400 mt-1">{incident.priority} · {incident.mode}</p></td><td className="p-3 align-top">{timing(incident.responseSeconds, incident.responseTargetSeconds, incident.responseStatus)}</td><td className="p-3 align-top">{timing(incident.resolutionSeconds, incident.resolutionTargetSeconds, incident.resolutionStatus)}</td><td className="p-3 align-top max-w-64 text-xs text-slate-500 dark:text-zinc-400"><p>{incident.clockBasis}</p><p className="font-mono mt-1">{incident.policyVersion}</p><details className="mt-1"><summary className="cursor-pointer">Recorded timestamps</summary><p>Ticket opened: {incident.startedAt || "Unknown"}</p><p>Response: {incident.responseAt || "Not recorded"}</p><p>Resolved: {incident.resolvedAt || "Not recorded"}</p></details></td></tr>)}</tbody></table></div>}
    <details className="text-xs text-slate-500 dark:text-zinc-400 mt-3"><summary className="cursor-pointer font-semibold">Incident clock methodology</summary><p className="mt-2">Resolution SLA commitments: P1 1 hour (3600s), P2 8 hours (28800s), P3 unconfigured. Timing uses the recorded ticket opening and resolution when available, as shown by each clock basis. Business-hours and pause calendars are not assumed. Missing trusted timing remains UNKNOWN; each row shows its recorded policy and target.</p></details>
  </section>;
}

export function ExperienceSurvey({ taskId, onSaved }: { key?: string; taskId: string; onSaved: () => Promise<void> }) {
  const [form, setForm] = useState(emptySurvey);
  const [busy, setBusy] = useState(false);
  const [message, setMessage] = useState("");
  const [error, setError] = useState("");
  async function submit(event: React.FormEvent) {
    event.preventDefault(); setBusy(true); setError(""); setMessage("");
    try {
      const response = await fetch("/api/observability/experience", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ taskId, helpfulness: Number(form.helpfulness), clarity: Number(form.clarity), trust: Number(form.trust), ease: Number(form.ease), helpedResolve: form.helpedResolve === "" ? null : form.helpedResolve === "yes", firstContactResolved: form.firstContactResolved === "" ? null : form.firstContactResolved === "yes", comment: form.comment }) });
      const body = await response.json(); if (!response.ok || body.success === false) throw new Error(body.error || "Feedback could not be saved.");
      await onSaved(); setMessage("Experience feedback saved. Your latest response for this task contributes to interaction feedback; previous responses remain in history.");
    } catch (e) { setError(e instanceof Error ? e.message : "Feedback could not be saved."); } finally { setBusy(false); }
  }
  return <form onSubmit={submit} className="border-t border-slate-200 dark:border-zinc-800 pt-4 space-y-3"><h5 className="font-semibold text-sm">Share your interaction feedback</h5><p className="text-xs text-slate-500 dark:text-zinc-400">Rate your experience with this completed task. Your opinion is separate from an expert review of whether the decision was correct.</p>
    <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">{([{ key: "helpfulness", label: "Helpfulness", low: "not helpful", high: "very helpful" }, { key: "clarity", label: "Clarity", low: "very unclear", high: "very clear" }, { key: "trust", label: "Trust", low: "no trust", high: "high trust" }, { key: "ease", label: "Ease / effort", low: "very hard", high: "very easy" }] as const).map(item => <label key={item.key} className="grid gap-1 text-xs">{item.label}<select required value={form[item.key]} className={input} onChange={e => setForm({ ...form, [item.key]: e.target.value })}><option value="">Select a rating</option>{[1, 2, 3, 4, 5].map(value => <option key={value} value={value}>{value}{value === 1 ? ` — ${item.low}` : value === 5 ? ` — ${item.high}` : ""}</option>)}</select><span className="text-slate-500 dark:text-zinc-400">1 = {item.low}; 5 = {item.high}</span></label>)}</div>
    {([{ key: "helpedResolve", label: "Did this help resolve your issue?" }, { key: "firstContactResolved", label: "Was your issue resolved on the first contact?" }] as const).map(item => <label key={item.key} className="grid gap-1 text-xs">{item.label}<select className={input} value={form[item.key]} onChange={e => setForm({ ...form, [item.key]: e.target.value })}><option value="">Not answered / not applicable</option><option value="yes">Yes</option><option value="no">No</option></select></label>)}
    <label className="grid gap-1 text-xs">What worked well or should improve? (optional)<textarea rows={3} maxLength={4000} className={input} value={form.comment} onChange={e => setForm({ ...form, comment: e.target.value })} /></label>
    {error && <p role="alert" className="text-sm text-red-700 dark:text-red-300">{error}</p>}{message && <p role="status" className="text-sm text-emerald-700 dark:text-emerald-300">{message}</p>}
    <button disabled={busy} className="px-4 py-2 text-sm rounded bg-indigo-600 text-white disabled:opacity-50 focus:ring-2 focus:ring-indigo-400">{busy ? "Saving feedback…" : "Save experience feedback"}</button>
  </form>;
}
