import type { DigitalTwinAgent, HITLApproval, IncidentAggregate, IncidentEvidence, ServiceNowIncident, SystemLog, WorkflowInstance } from '../../types';

export type DashboardEvent = { id: string; type: string; timestamp: string; incidentId?: string; correlationId?: string; payload: Record<string, unknown> };
export type EventCollection = { events: DashboardEvent[]; status: 'loading' | 'ready' | 'error' };
export type TwinDomain = 'Network' | 'Windows' | 'Linux' | 'Database' | 'Middleware' | 'CloudOps' | 'DevOps' | 'Cyber';
export interface DashboardEvidence { id: string; incidentId: string; workflowId?: string; domain?: TwinDomain; source: string; summary: string; observedAt: string; status: string; command?: string; output?: string; effect?: string; simulated: boolean; raw: IncidentEvidence }
export interface CollaborationStep { id: string; incidentId: string; workflowId?: string; sourceTwin: string; targetTwin: string; requestedCheck: string; status: 'REQUESTED' | 'RETURNED' | 'FAILED'; requestTime: string; responseTime?: string; plainEnglishRequest: string; plainEnglishResult?: string; evidenceIds: string[]; validatedEffect?: string; nextCheck?: string; raw: unknown }
export interface DashboardExecution { id: string; agent?: DigitalTwinAgent; domain: string; runtimeName: string; title: string; status: string; incident?: ServiceNowIncident; workflow?: WorkflowInstance; checksCompleted: number; checksTotal: number; checksLabel?: string; evidence: DashboardEvidence[]; evidenceAvailable: boolean; validatedState: string; latest: string; collaborations: CollaborationStep[] }
export interface DashboardTwin { domain: TwinDomain; agent?: DigitalTwinAgent; status: string; active: boolean; executionId?: string; hypothesis?: string }
export interface DashboardIncident { incident: ServiceNowIncident; owner: string; participants: Array<{ domain: string; state: string }>; state: string; hypothesis?: string; nextAction: string; activity: string; evidence: DashboardEvidence[]; checksCompleted: number; checksTotal: number; collaborations: CollaborationStep[]; dataStatus: EventCollection['status'] }
export interface DashboardOperation { id: string; timestamp: string; title: string; detail: string; kind: string; raw?: unknown }
export interface DashboardModel { twins: DashboardTwin[]; executions: DashboardExecution[]; incident?: DashboardIncident; operations: DashboardOperation[]; collaborations: CollaborationStep[]; evidenceCount?: number; activeIncidents: number; activeTwins: number; registeredTwins: number; pendingApprovals: HITLApproval[] }
export interface DashboardInput { agents: DigitalTwinAgent[]; workflows: WorkflowInstance[]; incidents: ServiceNowIncident[]; approvals: HITLApproval[]; systemLogs: SystemLog[]; aggregates?: IncidentAggregate[]; eventsByIncident: Record<string, EventCollection> }
