import { memo, useEffect, useState } from 'react';
import { motion } from 'motion/react';
import { Activity, ArrowRight, FileCheck2, Radio, Workflow, ShieldAlert } from 'lucide-react';
import type { OperatingMode } from '../../types';
import type { DashboardExecution, DashboardModel, DashboardOperation, DashboardTwin } from './model';
import { counterChange, DomainIcon, fadeUp, Status, Timestamp } from './presentation';
const Clock = memo(function Clock() {
  const [now, setNow] = useState(() => new Date());
  useEffect(() => { const timer = window.setInterval(() => setNow(new Date()), 60000); return () => window.clearInterval(timer); }, []);
  return <div className="cz-clock"><span>{now.toLocaleDateString(undefined, { day: '2-digit', month: 'short', year: 'numeric' })}</span><time dateTime={now.toISOString()}>{now.toLocaleTimeString(undefined, { hour: 'numeric', minute: '2-digit' })}</time></div>;
});
export function DashboardHeader({ name, mode }: { name: string; mode?: OperatingMode }) {
  return <header className="cz-dashboard-header"><div><p className="cz-eyebrow">Operations control</p><h1>Good day, {name.split(' ')[0]}</h1><p className="cz-subtitle"><strong>Digital Twin Operations</strong><span>Autonomous investigation and evidence-driven resolution</span></p></div><div className="cz-header-meta"><Clock /><span className="cz-mode">{mode ?? 'MODE UNKNOWN'}</span></div></header>;
}
export function OperationalStatusRail({ model: m, onApprovals }: { model: DashboardModel; onApprovals: () => void }) {
  const metrics = [{ label: 'Digital Twins', value: m.registeredTwins, sub: 'registered', icon: Workflow }, { label: 'Active now', value: m.activeTwins, sub: 'executing or waiting', icon: Radio }, { label: 'Active incidents', value: m.activeIncidents, sub: m.activeIncidents ? 'under investigation' : 'none active', icon: Activity }, { label: 'Evidence', value: m.evidenceCount ?? '—', sub: m.evidenceCount === undefined ? 'not available' : 'loaded records', icon: FileCheck2 }];
  return <div className="cz-status-rail" role="group" aria-label="Operational status">{metrics.map(m => <div className="cz-metric" key={m.label}><m.icon size={17} /><div><p>{m.label}</p><motion.strong key={m.value} variants={counterChange} initial="hidden" animate="visible">{m.value}</motion.strong><small>{m.sub}</small></div></div>)}{m.pendingApprovals.length > 0 && <button className="cz-attention" onClick={onApprovals}><ShieldAlert size={18} /><span><b>{m.pendingApprovals.length} approval{m.pendingApprovals.length === 1 ? '' : 's'}</b><small>Needs attention →</small></span></button>}</div>;
}
export function ActiveExecutions({ executions, onOpen }: { executions: DashboardExecution[]; onOpen: (id: string) => void }) {
  const [filter, setFilter] = useState('All');
  const [limit, setLimit] = useState(4);
  const matching = executions.filter(x => filter === 'All' || (filter === 'Incidents' ? !!(x.incident || x.workflow?.incidentId) : !(x.incident || x.workflow?.incidentId)));
  const visible = matching.slice(0, limit);
  return <section className="cz-executions"><header className="cz-section-heading"><div><p className="cz-eyebrow">Evidence workflow</p><h2>Active Twin Executions <span>{executions.length}</span></h2></div><div className="cz-filters" role="group" aria-label="Filter executions">{['All', 'Incidents', 'Automations'].map(f => <button key={f} aria-pressed={filter === f} onClick={() => { setFilter(f); setLimit(4); }}>{f}</button>)}</div></header><div className="cz-execution-grid">{visible.map(x => <motion.article key={x.id} variants={fadeUp} initial="hidden" animate="visible" className={`cz-execution ${(x.incident || x.workflow?.incidentId) ? 'cz-incident-execution' : ''}`}><header><div className="cz-domain-title"><DomainIcon domain={x.domain} /><div><h3>{x.domain} Twin</h3><p className="cz-runtime-name">{x.runtimeName}</p></div></div><Status value={x.status} /></header><p className="cz-execution-kind">{(x.incident || x.workflow?.incidentId) ? `INCIDENT · ${x.incident?.id ?? x.workflow?.incidentId}` : 'AUTOMATION'}</p><h4>{x.title}</h4><div className="cz-execution-observation"><small>{x.evidence.length ? 'Latest evidence' : 'Current activity'}</small><p>{x.latest}</p>{!x.incident && x.workflow?.incidentId && <p>Incident details restricted or unavailable.</p>}</div><div className="cz-execution-facts"><div><small>{x.checksLabel ?? 'Checks'}</small><b>{x.checksCompleted} / {x.checksTotal}</b></div><div><small>Evidence</small><b>{x.evidenceAvailable ? x.evidence.length : '—'}</b></div><div><small>Recorded guardrail</small><Status value={x.validatedState} /></div></div><button className="cz-text-button" onClick={() => onOpen(x.id)}>View Execution <ArrowRight size={14} /></button></motion.article>)}</div>{matching.length > 4 && <button className="cz-text-button cz-show-more" onClick={() => setLimit(limit >= matching.length ? 4 : limit + 4)}>{limit >= matching.length ? 'Show fewer' : `Show more executions (${matching.length - visible.length} remaining)`}</button>}{!visible.length && <div className="cz-empty"><Activity size={25} /><h3>No {filter === 'All' ? 'active executions' : filter.toLowerCase()}</h3><p>New runtime activity will appear here as Twins begin work.</p></div>}</section>;
}
export function LiveOperations({ operations, onActivity }: { operations: DashboardOperation[]; onActivity: () => void }) {
  return <aside className="cz-live-operations"><header className="cz-section-heading"><h2>Live Operations</h2><Radio size={15} /></header>{operations.length ? <ol className="cz-timeline">{operations.slice(0, 6).map(o => <motion.li key={o.id} variants={fadeUp} initial="hidden" animate="visible"><Timestamp value={o.timestamp} /><h3>{o.title}</h3><p>{o.detail}</p></motion.li>)}</ol> : <p className="cz-muted cz-live-empty">No recent operational activity.</p>}<button className="cz-text-button" onClick={onActivity}>View all activity <ArrowRight size={14} /></button></aside>;
}
export function AvailableTwinRoster({ twins, onOpen }: { twins: DashboardTwin[]; onOpen: (domain: string) => void }) {
  const idle = twins.filter(t => !t.active);
  return <section className="cz-roster"><header className="cz-section-heading"><h2>Available Twins</h2><span className="cz-muted">{idle.filter(t => t.status === 'AVAILABLE').length} ready</span></header><div className="cz-roster-items">{idle.map(t => <button key={t.domain} onClick={() => onOpen(t.domain)} disabled={!t.agent}><DomainIcon domain={t.domain} /><span><b>{t.domain}</b><Status value={t.status} /></span><ArrowRight size={13} /></button>)}</div>{!idle.length && <p className="cz-muted">All domain Twins are currently active.</p>}</section>;
}
